// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package path

import (
	context "context"
	endpoint "github.com/go-kit/kit/endpoint"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

type mixPathEndpoints struct {
	svc interface {
		MixPath(ctx context.Context, request *MixPathRequest) (*emptypb.Empty, error)
	}
}

func (e *mixPathEndpoints) MixPath() endpoint.Endpoint {
	return func(ctx context.Context, request any) (any, error) {
		return e.svc.MixPath(ctx, request.(*MixPathRequest))
	}
}

func NewmixPathEndpoints(
	svc interface {
		MixPath(ctx context.Context, request *MixPathRequest) (*emptypb.Empty, error)
	},
) interface {
	MixPath() endpoint.Endpoint
} {
	return &mixPathEndpoints{svc: svc}
}
