// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package path

import (
	cqrs "github.com/go-leo/leo/v3/cqrs"
)

// NamedPathAssembler responsible for completing the transformation between domain model objects and DTOs
type NamedPathAssembler interface {
}

// NamedPathCQRSService implement the NamedPath service with CQRS pattern
type NamedPathCQRSService struct {
	bus       cqrs.Bus
	assembler NamedPathAssembler
}

func NewNamedPathCQRSService(bus cqrs.Bus, assembler NamedPathAssembler) *NamedPathCQRSService {
	return &NamedPathCQRSService{bus: bus, assembler: assembler}
}

func NewNamedPathBus() (cqrs.Bus, error) {
	bus := cqrs.NewBus()
	return bus, nil
}
