// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package path

import (
	context "context"
	json "encoding/json"
	errors "errors"
	fmt "fmt"
	endpoint "github.com/go-kit/kit/endpoint"
	http "github.com/go-kit/kit/transport/http"
	strconvx "github.com/go-leo/gox/strconvx"
	endpointx "github.com/go-leo/leo/v3/endpointx"
	mux "github.com/gorilla/mux"
	proto "google.golang.org/protobuf/proto"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	io "io"
	http1 "net/http"
	url "net/url"
	strconv "strconv"
)

func NewPathHTTPServer(
	endpoints interface {
		BoolPath() endpoint.Endpoint
		Int32Path() endpoint.Endpoint
		Int64Path() endpoint.Endpoint
		Uint32Path() endpoint.Endpoint
		Uint64Path() endpoint.Endpoint
		FloatPath() endpoint.Endpoint
		DoublePath() endpoint.Endpoint
		StringPath() endpoint.Endpoint
		EnumPath() endpoint.Endpoint
	},
	mdw []endpoint.Middleware,
	opts ...http.ServerOption,
) http1.Handler {
	router := mux.NewRouter()
	router.NewRoute().
		Name("/leo.example.path.v1.Path/BoolPath").
		Methods("GET").
		Path("/v1/{bool}/{opt_bool}/{wrap_bool}").
		Handler(http.NewServer(
			endpointx.Chain(endpoints.BoolPath(), mdw...),
			func(ctx context.Context, r *http1.Request) (any, error) {
				req := &PathRequest{}
				vars := mux.Vars(r)
				_ = vars
				if v, err := strconvx.ParseBool(vars["bool"]); err != nil {
					return nil, err
				} else {
					req.Bool = v
				}
				if v, err := strconvx.ParseBool(vars["opt_bool"]); err != nil {
					return nil, err
				} else {
					req.OptBool = proto.Bool(v)
				}
				if v, err := strconvx.ParseBool(vars["wrap_bool"]); err != nil {
					return nil, err
				} else {
					req.WrapBool = wrapperspb.Bool(v)
				}
				queries := r.URL.Query()
				_ = queries
				if v, err := strconvx.ParseInt[int32](queries.Get("int32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Int32 = v
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("sint32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Sint32 = v
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("sfixed32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Sfixed32 = v
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("opt_int32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptInt32 = proto.Int32(v)
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("opt_sint32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptSint32 = proto.Int32(v)
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("opt_sfixed32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptSfixed32 = proto.Int32(v)
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("wrap_int32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.WrapInt32 = wrapperspb.Int32(v)
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("int64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.Int64 = v
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("sint64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.Sint64 = v
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("sfixed64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.Sfixed64 = v
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("opt_int64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.OptInt64 = proto.Int64(v)
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("opt_sint64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.OptSint64 = proto.Int64(v)
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("opt_sfixed64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.OptSfixed64 = proto.Int64(v)
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("wrap_int64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.WrapInt64 = wrapperspb.Int64(v)
				}
				if v, err := strconvx.ParseUint[uint32](queries.Get("uint32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Uint32 = v
				}
				if v, err := strconvx.ParseUint[uint32](queries.Get("fixed32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Fixed32 = v
				}
				if v, err := strconvx.ParseUint[uint32](queries.Get("opt_uint32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptUint32 = proto.Uint32(v)
				}
				if v, err := strconvx.ParseUint[uint32](queries.Get("opt_fixed32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptFixed32 = proto.Uint32(v)
				}
				if v, err := strconvx.ParseUint[uint32](queries.Get("wrap_uint32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.WrapUint32 = wrapperspb.UInt32(v)
				}
				if v, err := strconvx.ParseUint[uint64](queries.Get("uint64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.Uint64 = v
				}
				if v, err := strconvx.ParseUint[uint64](queries.Get("fixed64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.Fixed64 = v
				}
				if v, err := strconvx.ParseUint[uint64](queries.Get("opt_uint64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.OptUint64 = proto.Uint64(v)
				}
				if v, err := strconvx.ParseUint[uint64](queries.Get("opt_fixed64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.OptFixed64 = proto.Uint64(v)
				}
				if v, err := strconvx.ParseUint[uint64](queries.Get("wrap_uint64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.WrapUint64 = wrapperspb.UInt64(v)
				}
				if v, err := strconvx.ParseFloat[float32](queries.Get("float"), 32); err != nil {
					return nil, err
				} else {
					req.Float = v
				}
				if v, err := strconvx.ParseFloat[float32](queries.Get("opt_float"), 32); err != nil {
					return nil, err
				} else {
					req.OptFloat = proto.Float32(v)
				}
				if v, err := strconvx.ParseFloat[float32](queries.Get("wrap_float"), 32); err != nil {
					return nil, err
				} else {
					req.WrapFloat = wrapperspb.Float(v)
				}
				if v, err := strconvx.ParseFloat[float64](queries.Get("double"), 64); err != nil {
					return nil, err
				} else {
					req.Double = v
				}
				if v, err := strconvx.ParseFloat[float64](queries.Get("opt_double"), 64); err != nil {
					return nil, err
				} else {
					req.OptDouble = proto.Float64(v)
				}
				if v, err := strconvx.ParseFloat[float64](queries.Get("wrap_double"), 64); err != nil {
					return nil, err
				} else {
					req.WrapDouble = wrapperspb.Double(v)
				}
				req.String_ = queries.Get("string")
				req.OptString = proto.String(queries.Get("opt_string"))
				req.WrapString = wrapperspb.String(queries.Get("wrap_string"))
				if v, err := strconvx.ParseInt[PathRequest_Status](queries.Get("status"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Status = v
				}
				if v, err := strconvx.ParseInt[PathRequest_Status](queries.Get("opt_status"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptStatus = &v
				}
				return req, nil
			},
			func(ctx context.Context, w http1.ResponseWriter, obj any) error {
				resp := obj.(*emptypb.Empty)
				_ = resp
				w.WriteHeader(http1.StatusOK)
				data, err := json.Marshal(resp)
				if err != nil {
					return err
				}
				if _, err := w.Write(data); err != nil {
					return err
				}
				return nil
			},
			opts...,
		))
	router.NewRoute().
		Name("/leo.example.path.v1.Path/Int32Path").
		Methods("GET").
		Path("/v1/{int32}/{sint32}/{sfixed32}/{opt_int32}/{opt_sint32}/{opt_sfixed32}/{wrap_int32}").
		Handler(http.NewServer(
			endpointx.Chain(endpoints.Int32Path(), mdw...),
			func(ctx context.Context, r *http1.Request) (any, error) {
				req := &PathRequest{}
				vars := mux.Vars(r)
				_ = vars
				if v, err := strconvx.ParseInt[int32](vars["int32"], 10, 32); err != nil {
					return nil, err
				} else {
					req.Int32 = v
				}
				if v, err := strconvx.ParseInt[int32](vars["sint32"], 10, 32); err != nil {
					return nil, err
				} else {
					req.Sint32 = v
				}
				if v, err := strconvx.ParseInt[int32](vars["sfixed32"], 10, 32); err != nil {
					return nil, err
				} else {
					req.Sfixed32 = v
				}
				if v, err := strconvx.ParseInt[int32](vars["opt_int32"], 10, 32); err != nil {
					return nil, err
				} else {
					req.OptInt32 = proto.Int32(v)
				}
				if v, err := strconvx.ParseInt[int32](vars["opt_sint32"], 10, 32); err != nil {
					return nil, err
				} else {
					req.OptSint32 = proto.Int32(v)
				}
				if v, err := strconvx.ParseInt[int32](vars["opt_sfixed32"], 10, 32); err != nil {
					return nil, err
				} else {
					req.OptSfixed32 = proto.Int32(v)
				}
				if v, err := strconvx.ParseInt[int32](vars["wrap_int32"], 10, 32); err != nil {
					return nil, err
				} else {
					req.WrapInt32 = wrapperspb.Int32(v)
				}
				queries := r.URL.Query()
				_ = queries
				if v, err := strconvx.ParseBool(queries.Get("bool")); err != nil {
					return nil, err
				} else {
					req.Bool = v
				}
				if v, err := strconvx.ParseBool(queries.Get("opt_bool")); err != nil {
					return nil, err
				} else {
					req.OptBool = proto.Bool(v)
				}
				if v, err := strconvx.ParseBool(queries.Get("wrap_bool")); err != nil {
					return nil, err
				} else {
					req.WrapBool = wrapperspb.Bool(v)
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("int64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.Int64 = v
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("sint64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.Sint64 = v
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("sfixed64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.Sfixed64 = v
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("opt_int64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.OptInt64 = proto.Int64(v)
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("opt_sint64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.OptSint64 = proto.Int64(v)
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("opt_sfixed64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.OptSfixed64 = proto.Int64(v)
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("wrap_int64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.WrapInt64 = wrapperspb.Int64(v)
				}
				if v, err := strconvx.ParseUint[uint32](queries.Get("uint32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Uint32 = v
				}
				if v, err := strconvx.ParseUint[uint32](queries.Get("fixed32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Fixed32 = v
				}
				if v, err := strconvx.ParseUint[uint32](queries.Get("opt_uint32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptUint32 = proto.Uint32(v)
				}
				if v, err := strconvx.ParseUint[uint32](queries.Get("opt_fixed32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptFixed32 = proto.Uint32(v)
				}
				if v, err := strconvx.ParseUint[uint32](queries.Get("wrap_uint32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.WrapUint32 = wrapperspb.UInt32(v)
				}
				if v, err := strconvx.ParseUint[uint64](queries.Get("uint64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.Uint64 = v
				}
				if v, err := strconvx.ParseUint[uint64](queries.Get("fixed64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.Fixed64 = v
				}
				if v, err := strconvx.ParseUint[uint64](queries.Get("opt_uint64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.OptUint64 = proto.Uint64(v)
				}
				if v, err := strconvx.ParseUint[uint64](queries.Get("opt_fixed64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.OptFixed64 = proto.Uint64(v)
				}
				if v, err := strconvx.ParseUint[uint64](queries.Get("wrap_uint64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.WrapUint64 = wrapperspb.UInt64(v)
				}
				if v, err := strconvx.ParseFloat[float32](queries.Get("float"), 32); err != nil {
					return nil, err
				} else {
					req.Float = v
				}
				if v, err := strconvx.ParseFloat[float32](queries.Get("opt_float"), 32); err != nil {
					return nil, err
				} else {
					req.OptFloat = proto.Float32(v)
				}
				if v, err := strconvx.ParseFloat[float32](queries.Get("wrap_float"), 32); err != nil {
					return nil, err
				} else {
					req.WrapFloat = wrapperspb.Float(v)
				}
				if v, err := strconvx.ParseFloat[float64](queries.Get("double"), 64); err != nil {
					return nil, err
				} else {
					req.Double = v
				}
				if v, err := strconvx.ParseFloat[float64](queries.Get("opt_double"), 64); err != nil {
					return nil, err
				} else {
					req.OptDouble = proto.Float64(v)
				}
				if v, err := strconvx.ParseFloat[float64](queries.Get("wrap_double"), 64); err != nil {
					return nil, err
				} else {
					req.WrapDouble = wrapperspb.Double(v)
				}
				req.String_ = queries.Get("string")
				req.OptString = proto.String(queries.Get("opt_string"))
				req.WrapString = wrapperspb.String(queries.Get("wrap_string"))
				if v, err := strconvx.ParseInt[PathRequest_Status](queries.Get("status"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Status = v
				}
				if v, err := strconvx.ParseInt[PathRequest_Status](queries.Get("opt_status"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptStatus = &v
				}
				return req, nil
			},
			func(ctx context.Context, w http1.ResponseWriter, obj any) error {
				resp := obj.(*emptypb.Empty)
				_ = resp
				w.WriteHeader(http1.StatusOK)
				data, err := json.Marshal(resp)
				if err != nil {
					return err
				}
				if _, err := w.Write(data); err != nil {
					return err
				}
				return nil
			},
			opts...,
		))
	router.NewRoute().
		Name("/leo.example.path.v1.Path/Int64Path").
		Methods("GET").
		Path("/v1/{int64}/{sint64}/{sfixed64}/{opt_int64}/{opt_sint64}/{opt_sfixed64}/{wrap_int64}").
		Handler(http.NewServer(
			endpointx.Chain(endpoints.Int64Path(), mdw...),
			func(ctx context.Context, r *http1.Request) (any, error) {
				req := &PathRequest{}
				vars := mux.Vars(r)
				_ = vars
				if v, err := strconvx.ParseInt[int64](vars["int64"], 10, 64); err != nil {
					return nil, err
				} else {
					req.Int64 = v
				}
				if v, err := strconvx.ParseInt[int64](vars["sint64"], 10, 64); err != nil {
					return nil, err
				} else {
					req.Sint64 = v
				}
				if v, err := strconvx.ParseInt[int64](vars["sfixed64"], 10, 64); err != nil {
					return nil, err
				} else {
					req.Sfixed64 = v
				}
				if v, err := strconvx.ParseInt[int64](vars["opt_int64"], 10, 64); err != nil {
					return nil, err
				} else {
					req.OptInt64 = proto.Int64(v)
				}
				if v, err := strconvx.ParseInt[int64](vars["opt_sint64"], 10, 64); err != nil {
					return nil, err
				} else {
					req.OptSint64 = proto.Int64(v)
				}
				if v, err := strconvx.ParseInt[int64](vars["opt_sfixed64"], 10, 64); err != nil {
					return nil, err
				} else {
					req.OptSfixed64 = proto.Int64(v)
				}
				if v, err := strconvx.ParseInt[int64](vars["wrap_int64"], 10, 64); err != nil {
					return nil, err
				} else {
					req.WrapInt64 = wrapperspb.Int64(v)
				}
				queries := r.URL.Query()
				_ = queries
				if v, err := strconvx.ParseBool(queries.Get("bool")); err != nil {
					return nil, err
				} else {
					req.Bool = v
				}
				if v, err := strconvx.ParseBool(queries.Get("opt_bool")); err != nil {
					return nil, err
				} else {
					req.OptBool = proto.Bool(v)
				}
				if v, err := strconvx.ParseBool(queries.Get("wrap_bool")); err != nil {
					return nil, err
				} else {
					req.WrapBool = wrapperspb.Bool(v)
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("int32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Int32 = v
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("sint32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Sint32 = v
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("sfixed32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Sfixed32 = v
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("opt_int32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptInt32 = proto.Int32(v)
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("opt_sint32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptSint32 = proto.Int32(v)
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("opt_sfixed32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptSfixed32 = proto.Int32(v)
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("wrap_int32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.WrapInt32 = wrapperspb.Int32(v)
				}
				if v, err := strconvx.ParseUint[uint32](queries.Get("uint32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Uint32 = v
				}
				if v, err := strconvx.ParseUint[uint32](queries.Get("fixed32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Fixed32 = v
				}
				if v, err := strconvx.ParseUint[uint32](queries.Get("opt_uint32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptUint32 = proto.Uint32(v)
				}
				if v, err := strconvx.ParseUint[uint32](queries.Get("opt_fixed32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptFixed32 = proto.Uint32(v)
				}
				if v, err := strconvx.ParseUint[uint32](queries.Get("wrap_uint32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.WrapUint32 = wrapperspb.UInt32(v)
				}
				if v, err := strconvx.ParseUint[uint64](queries.Get("uint64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.Uint64 = v
				}
				if v, err := strconvx.ParseUint[uint64](queries.Get("fixed64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.Fixed64 = v
				}
				if v, err := strconvx.ParseUint[uint64](queries.Get("opt_uint64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.OptUint64 = proto.Uint64(v)
				}
				if v, err := strconvx.ParseUint[uint64](queries.Get("opt_fixed64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.OptFixed64 = proto.Uint64(v)
				}
				if v, err := strconvx.ParseUint[uint64](queries.Get("wrap_uint64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.WrapUint64 = wrapperspb.UInt64(v)
				}
				if v, err := strconvx.ParseFloat[float32](queries.Get("float"), 32); err != nil {
					return nil, err
				} else {
					req.Float = v
				}
				if v, err := strconvx.ParseFloat[float32](queries.Get("opt_float"), 32); err != nil {
					return nil, err
				} else {
					req.OptFloat = proto.Float32(v)
				}
				if v, err := strconvx.ParseFloat[float32](queries.Get("wrap_float"), 32); err != nil {
					return nil, err
				} else {
					req.WrapFloat = wrapperspb.Float(v)
				}
				if v, err := strconvx.ParseFloat[float64](queries.Get("double"), 64); err != nil {
					return nil, err
				} else {
					req.Double = v
				}
				if v, err := strconvx.ParseFloat[float64](queries.Get("opt_double"), 64); err != nil {
					return nil, err
				} else {
					req.OptDouble = proto.Float64(v)
				}
				if v, err := strconvx.ParseFloat[float64](queries.Get("wrap_double"), 64); err != nil {
					return nil, err
				} else {
					req.WrapDouble = wrapperspb.Double(v)
				}
				req.String_ = queries.Get("string")
				req.OptString = proto.String(queries.Get("opt_string"))
				req.WrapString = wrapperspb.String(queries.Get("wrap_string"))
				if v, err := strconvx.ParseInt[PathRequest_Status](queries.Get("status"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Status = v
				}
				if v, err := strconvx.ParseInt[PathRequest_Status](queries.Get("opt_status"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptStatus = &v
				}
				return req, nil
			},
			func(ctx context.Context, w http1.ResponseWriter, obj any) error {
				resp := obj.(*emptypb.Empty)
				_ = resp
				w.WriteHeader(http1.StatusOK)
				data, err := json.Marshal(resp)
				if err != nil {
					return err
				}
				if _, err := w.Write(data); err != nil {
					return err
				}
				return nil
			},
			opts...,
		))
	router.NewRoute().
		Name("/leo.example.path.v1.Path/Uint32Path").
		Methods("GET").
		Path("/v1/{uint32}/{fixed32}/{opt_uint32}/{opt_fixed32}/{wrap_uint32}").
		Handler(http.NewServer(
			endpointx.Chain(endpoints.Uint32Path(), mdw...),
			func(ctx context.Context, r *http1.Request) (any, error) {
				req := &PathRequest{}
				vars := mux.Vars(r)
				_ = vars
				if v, err := strconvx.ParseUint[uint32](vars["uint32"], 10, 32); err != nil {
					return nil, err
				} else {
					req.Uint32 = v
				}
				if v, err := strconvx.ParseUint[uint32](vars["fixed32"], 10, 32); err != nil {
					return nil, err
				} else {
					req.Fixed32 = v
				}
				if v, err := strconvx.ParseUint[uint32](vars["opt_uint32"], 10, 32); err != nil {
					return nil, err
				} else {
					req.OptUint32 = proto.Uint32(v)
				}
				if v, err := strconvx.ParseUint[uint32](vars["opt_fixed32"], 10, 32); err != nil {
					return nil, err
				} else {
					req.OptFixed32 = proto.Uint32(v)
				}
				if v, err := strconvx.ParseUint[uint32](vars["wrap_uint32"], 10, 32); err != nil {
					return nil, err
				} else {
					req.WrapUint32 = wrapperspb.UInt32(v)
				}
				queries := r.URL.Query()
				_ = queries
				if v, err := strconvx.ParseBool(queries.Get("bool")); err != nil {
					return nil, err
				} else {
					req.Bool = v
				}
				if v, err := strconvx.ParseBool(queries.Get("opt_bool")); err != nil {
					return nil, err
				} else {
					req.OptBool = proto.Bool(v)
				}
				if v, err := strconvx.ParseBool(queries.Get("wrap_bool")); err != nil {
					return nil, err
				} else {
					req.WrapBool = wrapperspb.Bool(v)
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("int32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Int32 = v
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("sint32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Sint32 = v
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("sfixed32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Sfixed32 = v
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("opt_int32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptInt32 = proto.Int32(v)
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("opt_sint32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptSint32 = proto.Int32(v)
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("opt_sfixed32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptSfixed32 = proto.Int32(v)
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("wrap_int32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.WrapInt32 = wrapperspb.Int32(v)
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("int64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.Int64 = v
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("sint64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.Sint64 = v
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("sfixed64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.Sfixed64 = v
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("opt_int64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.OptInt64 = proto.Int64(v)
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("opt_sint64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.OptSint64 = proto.Int64(v)
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("opt_sfixed64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.OptSfixed64 = proto.Int64(v)
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("wrap_int64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.WrapInt64 = wrapperspb.Int64(v)
				}
				if v, err := strconvx.ParseUint[uint64](queries.Get("uint64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.Uint64 = v
				}
				if v, err := strconvx.ParseUint[uint64](queries.Get("fixed64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.Fixed64 = v
				}
				if v, err := strconvx.ParseUint[uint64](queries.Get("opt_uint64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.OptUint64 = proto.Uint64(v)
				}
				if v, err := strconvx.ParseUint[uint64](queries.Get("opt_fixed64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.OptFixed64 = proto.Uint64(v)
				}
				if v, err := strconvx.ParseUint[uint64](queries.Get("wrap_uint64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.WrapUint64 = wrapperspb.UInt64(v)
				}
				if v, err := strconvx.ParseFloat[float32](queries.Get("float"), 32); err != nil {
					return nil, err
				} else {
					req.Float = v
				}
				if v, err := strconvx.ParseFloat[float32](queries.Get("opt_float"), 32); err != nil {
					return nil, err
				} else {
					req.OptFloat = proto.Float32(v)
				}
				if v, err := strconvx.ParseFloat[float32](queries.Get("wrap_float"), 32); err != nil {
					return nil, err
				} else {
					req.WrapFloat = wrapperspb.Float(v)
				}
				if v, err := strconvx.ParseFloat[float64](queries.Get("double"), 64); err != nil {
					return nil, err
				} else {
					req.Double = v
				}
				if v, err := strconvx.ParseFloat[float64](queries.Get("opt_double"), 64); err != nil {
					return nil, err
				} else {
					req.OptDouble = proto.Float64(v)
				}
				if v, err := strconvx.ParseFloat[float64](queries.Get("wrap_double"), 64); err != nil {
					return nil, err
				} else {
					req.WrapDouble = wrapperspb.Double(v)
				}
				req.String_ = queries.Get("string")
				req.OptString = proto.String(queries.Get("opt_string"))
				req.WrapString = wrapperspb.String(queries.Get("wrap_string"))
				if v, err := strconvx.ParseInt[PathRequest_Status](queries.Get("status"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Status = v
				}
				if v, err := strconvx.ParseInt[PathRequest_Status](queries.Get("opt_status"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptStatus = &v
				}
				return req, nil
			},
			func(ctx context.Context, w http1.ResponseWriter, obj any) error {
				resp := obj.(*emptypb.Empty)
				_ = resp
				w.WriteHeader(http1.StatusOK)
				data, err := json.Marshal(resp)
				if err != nil {
					return err
				}
				if _, err := w.Write(data); err != nil {
					return err
				}
				return nil
			},
			opts...,
		))
	router.NewRoute().
		Name("/leo.example.path.v1.Path/Uint64Path").
		Methods("GET").
		Path("/v1/{uint64}/{fixed64}/{opt_uint64}/{opt_fixed64}/{wrap_uint64}").
		Handler(http.NewServer(
			endpointx.Chain(endpoints.Uint64Path(), mdw...),
			func(ctx context.Context, r *http1.Request) (any, error) {
				req := &PathRequest{}
				vars := mux.Vars(r)
				_ = vars
				if v, err := strconvx.ParseUint[uint64](vars["uint64"], 10, 64); err != nil {
					return nil, err
				} else {
					req.Uint64 = v
				}
				if v, err := strconvx.ParseUint[uint64](vars["fixed64"], 10, 64); err != nil {
					return nil, err
				} else {
					req.Fixed64 = v
				}
				if v, err := strconvx.ParseUint[uint64](vars["opt_uint64"], 10, 64); err != nil {
					return nil, err
				} else {
					req.OptUint64 = proto.Uint64(v)
				}
				if v, err := strconvx.ParseUint[uint64](vars["opt_fixed64"], 10, 64); err != nil {
					return nil, err
				} else {
					req.OptFixed64 = proto.Uint64(v)
				}
				if v, err := strconvx.ParseUint[uint64](vars["wrap_uint64"], 10, 64); err != nil {
					return nil, err
				} else {
					req.WrapUint64 = wrapperspb.UInt64(v)
				}
				queries := r.URL.Query()
				_ = queries
				if v, err := strconvx.ParseBool(queries.Get("bool")); err != nil {
					return nil, err
				} else {
					req.Bool = v
				}
				if v, err := strconvx.ParseBool(queries.Get("opt_bool")); err != nil {
					return nil, err
				} else {
					req.OptBool = proto.Bool(v)
				}
				if v, err := strconvx.ParseBool(queries.Get("wrap_bool")); err != nil {
					return nil, err
				} else {
					req.WrapBool = wrapperspb.Bool(v)
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("int32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Int32 = v
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("sint32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Sint32 = v
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("sfixed32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Sfixed32 = v
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("opt_int32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptInt32 = proto.Int32(v)
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("opt_sint32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptSint32 = proto.Int32(v)
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("opt_sfixed32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptSfixed32 = proto.Int32(v)
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("wrap_int32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.WrapInt32 = wrapperspb.Int32(v)
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("int64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.Int64 = v
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("sint64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.Sint64 = v
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("sfixed64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.Sfixed64 = v
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("opt_int64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.OptInt64 = proto.Int64(v)
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("opt_sint64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.OptSint64 = proto.Int64(v)
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("opt_sfixed64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.OptSfixed64 = proto.Int64(v)
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("wrap_int64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.WrapInt64 = wrapperspb.Int64(v)
				}
				if v, err := strconvx.ParseUint[uint32](queries.Get("uint32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Uint32 = v
				}
				if v, err := strconvx.ParseUint[uint32](queries.Get("fixed32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Fixed32 = v
				}
				if v, err := strconvx.ParseUint[uint32](queries.Get("opt_uint32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptUint32 = proto.Uint32(v)
				}
				if v, err := strconvx.ParseUint[uint32](queries.Get("opt_fixed32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptFixed32 = proto.Uint32(v)
				}
				if v, err := strconvx.ParseUint[uint32](queries.Get("wrap_uint32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.WrapUint32 = wrapperspb.UInt32(v)
				}
				if v, err := strconvx.ParseFloat[float32](queries.Get("float"), 32); err != nil {
					return nil, err
				} else {
					req.Float = v
				}
				if v, err := strconvx.ParseFloat[float32](queries.Get("opt_float"), 32); err != nil {
					return nil, err
				} else {
					req.OptFloat = proto.Float32(v)
				}
				if v, err := strconvx.ParseFloat[float32](queries.Get("wrap_float"), 32); err != nil {
					return nil, err
				} else {
					req.WrapFloat = wrapperspb.Float(v)
				}
				if v, err := strconvx.ParseFloat[float64](queries.Get("double"), 64); err != nil {
					return nil, err
				} else {
					req.Double = v
				}
				if v, err := strconvx.ParseFloat[float64](queries.Get("opt_double"), 64); err != nil {
					return nil, err
				} else {
					req.OptDouble = proto.Float64(v)
				}
				if v, err := strconvx.ParseFloat[float64](queries.Get("wrap_double"), 64); err != nil {
					return nil, err
				} else {
					req.WrapDouble = wrapperspb.Double(v)
				}
				req.String_ = queries.Get("string")
				req.OptString = proto.String(queries.Get("opt_string"))
				req.WrapString = wrapperspb.String(queries.Get("wrap_string"))
				if v, err := strconvx.ParseInt[PathRequest_Status](queries.Get("status"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Status = v
				}
				if v, err := strconvx.ParseInt[PathRequest_Status](queries.Get("opt_status"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptStatus = &v
				}
				return req, nil
			},
			func(ctx context.Context, w http1.ResponseWriter, obj any) error {
				resp := obj.(*emptypb.Empty)
				_ = resp
				w.WriteHeader(http1.StatusOK)
				data, err := json.Marshal(resp)
				if err != nil {
					return err
				}
				if _, err := w.Write(data); err != nil {
					return err
				}
				return nil
			},
			opts...,
		))
	router.NewRoute().
		Name("/leo.example.path.v1.Path/FloatPath").
		Methods("GET").
		Path("/v1/{float}/{opt_float}/{wrap_float}").
		Handler(http.NewServer(
			endpointx.Chain(endpoints.FloatPath(), mdw...),
			func(ctx context.Context, r *http1.Request) (any, error) {
				req := &PathRequest{}
				vars := mux.Vars(r)
				_ = vars
				if v, err := strconvx.ParseFloat[float32](vars["float"], 32); err != nil {
					return nil, err
				} else {
					req.Float = v
				}
				if v, err := strconvx.ParseFloat[float32](vars["opt_float"], 32); err != nil {
					return nil, err
				} else {
					req.OptFloat = proto.Float32(v)
				}
				if v, err := strconvx.ParseFloat[float32](vars["wrap_float"], 32); err != nil {
					return nil, err
				} else {
					req.WrapFloat = wrapperspb.Float(v)
				}
				queries := r.URL.Query()
				_ = queries
				if v, err := strconvx.ParseBool(queries.Get("bool")); err != nil {
					return nil, err
				} else {
					req.Bool = v
				}
				if v, err := strconvx.ParseBool(queries.Get("opt_bool")); err != nil {
					return nil, err
				} else {
					req.OptBool = proto.Bool(v)
				}
				if v, err := strconvx.ParseBool(queries.Get("wrap_bool")); err != nil {
					return nil, err
				} else {
					req.WrapBool = wrapperspb.Bool(v)
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("int32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Int32 = v
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("sint32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Sint32 = v
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("sfixed32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Sfixed32 = v
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("opt_int32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptInt32 = proto.Int32(v)
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("opt_sint32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptSint32 = proto.Int32(v)
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("opt_sfixed32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptSfixed32 = proto.Int32(v)
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("wrap_int32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.WrapInt32 = wrapperspb.Int32(v)
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("int64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.Int64 = v
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("sint64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.Sint64 = v
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("sfixed64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.Sfixed64 = v
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("opt_int64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.OptInt64 = proto.Int64(v)
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("opt_sint64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.OptSint64 = proto.Int64(v)
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("opt_sfixed64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.OptSfixed64 = proto.Int64(v)
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("wrap_int64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.WrapInt64 = wrapperspb.Int64(v)
				}
				if v, err := strconvx.ParseUint[uint32](queries.Get("uint32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Uint32 = v
				}
				if v, err := strconvx.ParseUint[uint32](queries.Get("fixed32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Fixed32 = v
				}
				if v, err := strconvx.ParseUint[uint32](queries.Get("opt_uint32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptUint32 = proto.Uint32(v)
				}
				if v, err := strconvx.ParseUint[uint32](queries.Get("opt_fixed32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptFixed32 = proto.Uint32(v)
				}
				if v, err := strconvx.ParseUint[uint32](queries.Get("wrap_uint32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.WrapUint32 = wrapperspb.UInt32(v)
				}
				if v, err := strconvx.ParseUint[uint64](queries.Get("uint64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.Uint64 = v
				}
				if v, err := strconvx.ParseUint[uint64](queries.Get("fixed64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.Fixed64 = v
				}
				if v, err := strconvx.ParseUint[uint64](queries.Get("opt_uint64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.OptUint64 = proto.Uint64(v)
				}
				if v, err := strconvx.ParseUint[uint64](queries.Get("opt_fixed64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.OptFixed64 = proto.Uint64(v)
				}
				if v, err := strconvx.ParseUint[uint64](queries.Get("wrap_uint64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.WrapUint64 = wrapperspb.UInt64(v)
				}
				if v, err := strconvx.ParseFloat[float64](queries.Get("double"), 64); err != nil {
					return nil, err
				} else {
					req.Double = v
				}
				if v, err := strconvx.ParseFloat[float64](queries.Get("opt_double"), 64); err != nil {
					return nil, err
				} else {
					req.OptDouble = proto.Float64(v)
				}
				if v, err := strconvx.ParseFloat[float64](queries.Get("wrap_double"), 64); err != nil {
					return nil, err
				} else {
					req.WrapDouble = wrapperspb.Double(v)
				}
				req.String_ = queries.Get("string")
				req.OptString = proto.String(queries.Get("opt_string"))
				req.WrapString = wrapperspb.String(queries.Get("wrap_string"))
				if v, err := strconvx.ParseInt[PathRequest_Status](queries.Get("status"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Status = v
				}
				if v, err := strconvx.ParseInt[PathRequest_Status](queries.Get("opt_status"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptStatus = &v
				}
				return req, nil
			},
			func(ctx context.Context, w http1.ResponseWriter, obj any) error {
				resp := obj.(*emptypb.Empty)
				_ = resp
				w.WriteHeader(http1.StatusOK)
				data, err := json.Marshal(resp)
				if err != nil {
					return err
				}
				if _, err := w.Write(data); err != nil {
					return err
				}
				return nil
			},
			opts...,
		))
	router.NewRoute().
		Name("/leo.example.path.v1.Path/DoublePath").
		Methods("GET").
		Path("/v1/{double}/{opt_double}/{wrap_double}").
		Handler(http.NewServer(
			endpointx.Chain(endpoints.DoublePath(), mdw...),
			func(ctx context.Context, r *http1.Request) (any, error) {
				req := &PathRequest{}
				vars := mux.Vars(r)
				_ = vars
				if v, err := strconvx.ParseFloat[float64](vars["double"], 64); err != nil {
					return nil, err
				} else {
					req.Double = v
				}
				if v, err := strconvx.ParseFloat[float64](vars["opt_double"], 64); err != nil {
					return nil, err
				} else {
					req.OptDouble = proto.Float64(v)
				}
				if v, err := strconvx.ParseFloat[float64](vars["wrap_double"], 64); err != nil {
					return nil, err
				} else {
					req.WrapDouble = wrapperspb.Double(v)
				}
				queries := r.URL.Query()
				_ = queries
				if v, err := strconvx.ParseBool(queries.Get("bool")); err != nil {
					return nil, err
				} else {
					req.Bool = v
				}
				if v, err := strconvx.ParseBool(queries.Get("opt_bool")); err != nil {
					return nil, err
				} else {
					req.OptBool = proto.Bool(v)
				}
				if v, err := strconvx.ParseBool(queries.Get("wrap_bool")); err != nil {
					return nil, err
				} else {
					req.WrapBool = wrapperspb.Bool(v)
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("int32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Int32 = v
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("sint32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Sint32 = v
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("sfixed32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Sfixed32 = v
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("opt_int32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptInt32 = proto.Int32(v)
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("opt_sint32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptSint32 = proto.Int32(v)
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("opt_sfixed32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptSfixed32 = proto.Int32(v)
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("wrap_int32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.WrapInt32 = wrapperspb.Int32(v)
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("int64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.Int64 = v
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("sint64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.Sint64 = v
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("sfixed64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.Sfixed64 = v
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("opt_int64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.OptInt64 = proto.Int64(v)
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("opt_sint64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.OptSint64 = proto.Int64(v)
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("opt_sfixed64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.OptSfixed64 = proto.Int64(v)
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("wrap_int64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.WrapInt64 = wrapperspb.Int64(v)
				}
				if v, err := strconvx.ParseUint[uint32](queries.Get("uint32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Uint32 = v
				}
				if v, err := strconvx.ParseUint[uint32](queries.Get("fixed32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Fixed32 = v
				}
				if v, err := strconvx.ParseUint[uint32](queries.Get("opt_uint32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptUint32 = proto.Uint32(v)
				}
				if v, err := strconvx.ParseUint[uint32](queries.Get("opt_fixed32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptFixed32 = proto.Uint32(v)
				}
				if v, err := strconvx.ParseUint[uint32](queries.Get("wrap_uint32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.WrapUint32 = wrapperspb.UInt32(v)
				}
				if v, err := strconvx.ParseUint[uint64](queries.Get("uint64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.Uint64 = v
				}
				if v, err := strconvx.ParseUint[uint64](queries.Get("fixed64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.Fixed64 = v
				}
				if v, err := strconvx.ParseUint[uint64](queries.Get("opt_uint64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.OptUint64 = proto.Uint64(v)
				}
				if v, err := strconvx.ParseUint[uint64](queries.Get("opt_fixed64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.OptFixed64 = proto.Uint64(v)
				}
				if v, err := strconvx.ParseUint[uint64](queries.Get("wrap_uint64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.WrapUint64 = wrapperspb.UInt64(v)
				}
				if v, err := strconvx.ParseFloat[float32](queries.Get("float"), 32); err != nil {
					return nil, err
				} else {
					req.Float = v
				}
				if v, err := strconvx.ParseFloat[float32](queries.Get("opt_float"), 32); err != nil {
					return nil, err
				} else {
					req.OptFloat = proto.Float32(v)
				}
				if v, err := strconvx.ParseFloat[float32](queries.Get("wrap_float"), 32); err != nil {
					return nil, err
				} else {
					req.WrapFloat = wrapperspb.Float(v)
				}
				req.String_ = queries.Get("string")
				req.OptString = proto.String(queries.Get("opt_string"))
				req.WrapString = wrapperspb.String(queries.Get("wrap_string"))
				if v, err := strconvx.ParseInt[PathRequest_Status](queries.Get("status"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Status = v
				}
				if v, err := strconvx.ParseInt[PathRequest_Status](queries.Get("opt_status"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptStatus = &v
				}
				return req, nil
			},
			func(ctx context.Context, w http1.ResponseWriter, obj any) error {
				resp := obj.(*emptypb.Empty)
				_ = resp
				w.WriteHeader(http1.StatusOK)
				data, err := json.Marshal(resp)
				if err != nil {
					return err
				}
				if _, err := w.Write(data); err != nil {
					return err
				}
				return nil
			},
			opts...,
		))
	router.NewRoute().
		Name("/leo.example.path.v1.Path/StringPath").
		Methods("GET").
		Path("/v1/{string}/{opt_string}/{wrap_string}").
		Handler(http.NewServer(
			endpointx.Chain(endpoints.StringPath(), mdw...),
			func(ctx context.Context, r *http1.Request) (any, error) {
				req := &PathRequest{}
				vars := mux.Vars(r)
				_ = vars
				req.String_ = vars["string"]
				req.OptString = proto.String(vars["opt_string"])
				req.WrapString = wrapperspb.String(vars["wrap_string"])
				queries := r.URL.Query()
				_ = queries
				if v, err := strconvx.ParseBool(queries.Get("bool")); err != nil {
					return nil, err
				} else {
					req.Bool = v
				}
				if v, err := strconvx.ParseBool(queries.Get("opt_bool")); err != nil {
					return nil, err
				} else {
					req.OptBool = proto.Bool(v)
				}
				if v, err := strconvx.ParseBool(queries.Get("wrap_bool")); err != nil {
					return nil, err
				} else {
					req.WrapBool = wrapperspb.Bool(v)
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("int32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Int32 = v
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("sint32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Sint32 = v
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("sfixed32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Sfixed32 = v
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("opt_int32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptInt32 = proto.Int32(v)
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("opt_sint32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptSint32 = proto.Int32(v)
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("opt_sfixed32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptSfixed32 = proto.Int32(v)
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("wrap_int32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.WrapInt32 = wrapperspb.Int32(v)
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("int64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.Int64 = v
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("sint64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.Sint64 = v
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("sfixed64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.Sfixed64 = v
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("opt_int64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.OptInt64 = proto.Int64(v)
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("opt_sint64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.OptSint64 = proto.Int64(v)
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("opt_sfixed64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.OptSfixed64 = proto.Int64(v)
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("wrap_int64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.WrapInt64 = wrapperspb.Int64(v)
				}
				if v, err := strconvx.ParseUint[uint32](queries.Get("uint32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Uint32 = v
				}
				if v, err := strconvx.ParseUint[uint32](queries.Get("fixed32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Fixed32 = v
				}
				if v, err := strconvx.ParseUint[uint32](queries.Get("opt_uint32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptUint32 = proto.Uint32(v)
				}
				if v, err := strconvx.ParseUint[uint32](queries.Get("opt_fixed32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptFixed32 = proto.Uint32(v)
				}
				if v, err := strconvx.ParseUint[uint32](queries.Get("wrap_uint32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.WrapUint32 = wrapperspb.UInt32(v)
				}
				if v, err := strconvx.ParseUint[uint64](queries.Get("uint64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.Uint64 = v
				}
				if v, err := strconvx.ParseUint[uint64](queries.Get("fixed64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.Fixed64 = v
				}
				if v, err := strconvx.ParseUint[uint64](queries.Get("opt_uint64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.OptUint64 = proto.Uint64(v)
				}
				if v, err := strconvx.ParseUint[uint64](queries.Get("opt_fixed64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.OptFixed64 = proto.Uint64(v)
				}
				if v, err := strconvx.ParseUint[uint64](queries.Get("wrap_uint64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.WrapUint64 = wrapperspb.UInt64(v)
				}
				if v, err := strconvx.ParseFloat[float32](queries.Get("float"), 32); err != nil {
					return nil, err
				} else {
					req.Float = v
				}
				if v, err := strconvx.ParseFloat[float32](queries.Get("opt_float"), 32); err != nil {
					return nil, err
				} else {
					req.OptFloat = proto.Float32(v)
				}
				if v, err := strconvx.ParseFloat[float32](queries.Get("wrap_float"), 32); err != nil {
					return nil, err
				} else {
					req.WrapFloat = wrapperspb.Float(v)
				}
				if v, err := strconvx.ParseFloat[float64](queries.Get("double"), 64); err != nil {
					return nil, err
				} else {
					req.Double = v
				}
				if v, err := strconvx.ParseFloat[float64](queries.Get("opt_double"), 64); err != nil {
					return nil, err
				} else {
					req.OptDouble = proto.Float64(v)
				}
				if v, err := strconvx.ParseFloat[float64](queries.Get("wrap_double"), 64); err != nil {
					return nil, err
				} else {
					req.WrapDouble = wrapperspb.Double(v)
				}
				if v, err := strconvx.ParseInt[PathRequest_Status](queries.Get("status"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Status = v
				}
				if v, err := strconvx.ParseInt[PathRequest_Status](queries.Get("opt_status"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptStatus = &v
				}
				return req, nil
			},
			func(ctx context.Context, w http1.ResponseWriter, obj any) error {
				resp := obj.(*emptypb.Empty)
				_ = resp
				w.WriteHeader(http1.StatusOK)
				data, err := json.Marshal(resp)
				if err != nil {
					return err
				}
				if _, err := w.Write(data); err != nil {
					return err
				}
				return nil
			},
			opts...,
		))
	router.NewRoute().
		Name("/leo.example.path.v1.Path/EnumPath").
		Methods("GET").
		Path("/v1/{status}/{opt_status}").
		Handler(http.NewServer(
			endpointx.Chain(endpoints.EnumPath(), mdw...),
			func(ctx context.Context, r *http1.Request) (any, error) {
				req := &PathRequest{}
				vars := mux.Vars(r)
				_ = vars
				if v, err := strconvx.ParseInt[PathRequest_Status](vars["status"], 10, 32); err != nil {
					return nil, err
				} else {
					req.Status = v
				}
				if v, err := strconvx.ParseInt[PathRequest_Status](vars["opt_status"], 10, 32); err != nil {
					return nil, err
				} else {
					req.OptStatus = &v
				}
				queries := r.URL.Query()
				_ = queries
				if v, err := strconvx.ParseBool(queries.Get("bool")); err != nil {
					return nil, err
				} else {
					req.Bool = v
				}
				if v, err := strconvx.ParseBool(queries.Get("opt_bool")); err != nil {
					return nil, err
				} else {
					req.OptBool = proto.Bool(v)
				}
				if v, err := strconvx.ParseBool(queries.Get("wrap_bool")); err != nil {
					return nil, err
				} else {
					req.WrapBool = wrapperspb.Bool(v)
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("int32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Int32 = v
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("sint32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Sint32 = v
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("sfixed32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Sfixed32 = v
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("opt_int32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptInt32 = proto.Int32(v)
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("opt_sint32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptSint32 = proto.Int32(v)
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("opt_sfixed32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptSfixed32 = proto.Int32(v)
				}
				if v, err := strconvx.ParseInt[int32](queries.Get("wrap_int32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.WrapInt32 = wrapperspb.Int32(v)
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("int64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.Int64 = v
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("sint64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.Sint64 = v
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("sfixed64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.Sfixed64 = v
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("opt_int64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.OptInt64 = proto.Int64(v)
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("opt_sint64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.OptSint64 = proto.Int64(v)
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("opt_sfixed64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.OptSfixed64 = proto.Int64(v)
				}
				if v, err := strconvx.ParseInt[int64](queries.Get("wrap_int64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.WrapInt64 = wrapperspb.Int64(v)
				}
				if v, err := strconvx.ParseUint[uint32](queries.Get("uint32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Uint32 = v
				}
				if v, err := strconvx.ParseUint[uint32](queries.Get("fixed32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.Fixed32 = v
				}
				if v, err := strconvx.ParseUint[uint32](queries.Get("opt_uint32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptUint32 = proto.Uint32(v)
				}
				if v, err := strconvx.ParseUint[uint32](queries.Get("opt_fixed32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.OptFixed32 = proto.Uint32(v)
				}
				if v, err := strconvx.ParseUint[uint32](queries.Get("wrap_uint32"), 10, 32); err != nil {
					return nil, err
				} else {
					req.WrapUint32 = wrapperspb.UInt32(v)
				}
				if v, err := strconvx.ParseUint[uint64](queries.Get("uint64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.Uint64 = v
				}
				if v, err := strconvx.ParseUint[uint64](queries.Get("fixed64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.Fixed64 = v
				}
				if v, err := strconvx.ParseUint[uint64](queries.Get("opt_uint64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.OptUint64 = proto.Uint64(v)
				}
				if v, err := strconvx.ParseUint[uint64](queries.Get("opt_fixed64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.OptFixed64 = proto.Uint64(v)
				}
				if v, err := strconvx.ParseUint[uint64](queries.Get("wrap_uint64"), 10, 64); err != nil {
					return nil, err
				} else {
					req.WrapUint64 = wrapperspb.UInt64(v)
				}
				if v, err := strconvx.ParseFloat[float32](queries.Get("float"), 32); err != nil {
					return nil, err
				} else {
					req.Float = v
				}
				if v, err := strconvx.ParseFloat[float32](queries.Get("opt_float"), 32); err != nil {
					return nil, err
				} else {
					req.OptFloat = proto.Float32(v)
				}
				if v, err := strconvx.ParseFloat[float32](queries.Get("wrap_float"), 32); err != nil {
					return nil, err
				} else {
					req.WrapFloat = wrapperspb.Float(v)
				}
				if v, err := strconvx.ParseFloat[float64](queries.Get("double"), 64); err != nil {
					return nil, err
				} else {
					req.Double = v
				}
				if v, err := strconvx.ParseFloat[float64](queries.Get("opt_double"), 64); err != nil {
					return nil, err
				} else {
					req.OptDouble = proto.Float64(v)
				}
				if v, err := strconvx.ParseFloat[float64](queries.Get("wrap_double"), 64); err != nil {
					return nil, err
				} else {
					req.WrapDouble = wrapperspb.Double(v)
				}
				req.String_ = queries.Get("string")
				req.OptString = proto.String(queries.Get("opt_string"))
				req.WrapString = wrapperspb.String(queries.Get("wrap_string"))
				return req, nil
			},
			func(ctx context.Context, w http1.ResponseWriter, obj any) error {
				resp := obj.(*emptypb.Empty)
				_ = resp
				w.WriteHeader(http1.StatusOK)
				data, err := json.Marshal(resp)
				if err != nil {
					return err
				}
				if _, err := w.Write(data); err != nil {
					return err
				}
				return nil
			},
			opts...,
		))
	return router
}

type pathHTTPClient struct {
	boolPath   endpoint.Endpoint
	int32Path  endpoint.Endpoint
	int64Path  endpoint.Endpoint
	uint32Path endpoint.Endpoint
	uint64Path endpoint.Endpoint
	floatPath  endpoint.Endpoint
	doublePath endpoint.Endpoint
	stringPath endpoint.Endpoint
	enumPath   endpoint.Endpoint
}

func (c *pathHTTPClient) BoolPath(ctx context.Context, request *PathRequest) (*emptypb.Empty, error) {
	rep, err := c.boolPath(ctx, request)
	if err != nil {
		return nil, err
	}
	return rep.(*emptypb.Empty), nil
}

func (c *pathHTTPClient) Int32Path(ctx context.Context, request *PathRequest) (*emptypb.Empty, error) {
	rep, err := c.int32Path(ctx, request)
	if err != nil {
		return nil, err
	}
	return rep.(*emptypb.Empty), nil
}

func (c *pathHTTPClient) Int64Path(ctx context.Context, request *PathRequest) (*emptypb.Empty, error) {
	rep, err := c.int64Path(ctx, request)
	if err != nil {
		return nil, err
	}
	return rep.(*emptypb.Empty), nil
}

func (c *pathHTTPClient) Uint32Path(ctx context.Context, request *PathRequest) (*emptypb.Empty, error) {
	rep, err := c.uint32Path(ctx, request)
	if err != nil {
		return nil, err
	}
	return rep.(*emptypb.Empty), nil
}

func (c *pathHTTPClient) Uint64Path(ctx context.Context, request *PathRequest) (*emptypb.Empty, error) {
	rep, err := c.uint64Path(ctx, request)
	if err != nil {
		return nil, err
	}
	return rep.(*emptypb.Empty), nil
}

func (c *pathHTTPClient) FloatPath(ctx context.Context, request *PathRequest) (*emptypb.Empty, error) {
	rep, err := c.floatPath(ctx, request)
	if err != nil {
		return nil, err
	}
	return rep.(*emptypb.Empty), nil
}

func (c *pathHTTPClient) DoublePath(ctx context.Context, request *PathRequest) (*emptypb.Empty, error) {
	rep, err := c.doublePath(ctx, request)
	if err != nil {
		return nil, err
	}
	return rep.(*emptypb.Empty), nil
}

func (c *pathHTTPClient) StringPath(ctx context.Context, request *PathRequest) (*emptypb.Empty, error) {
	rep, err := c.stringPath(ctx, request)
	if err != nil {
		return nil, err
	}
	return rep.(*emptypb.Empty), nil
}

func (c *pathHTTPClient) EnumPath(ctx context.Context, request *PathRequest) (*emptypb.Empty, error) {
	rep, err := c.enumPath(ctx, request)
	if err != nil {
		return nil, err
	}
	return rep.(*emptypb.Empty), nil
}

func NewPathHTTPClient(
	scheme string,
	instance string,
	mdw []endpoint.Middleware,
	opts ...http.ClientOption,
) interface {
	BoolPath(ctx context.Context, request *PathRequest) (*emptypb.Empty, error)
	Int32Path(ctx context.Context, request *PathRequest) (*emptypb.Empty, error)
	Int64Path(ctx context.Context, request *PathRequest) (*emptypb.Empty, error)
	Uint32Path(ctx context.Context, request *PathRequest) (*emptypb.Empty, error)
	Uint64Path(ctx context.Context, request *PathRequest) (*emptypb.Empty, error)
	FloatPath(ctx context.Context, request *PathRequest) (*emptypb.Empty, error)
	DoublePath(ctx context.Context, request *PathRequest) (*emptypb.Empty, error)
	StringPath(ctx context.Context, request *PathRequest) (*emptypb.Empty, error)
	EnumPath(ctx context.Context, request *PathRequest) (*emptypb.Empty, error)
} {
	router := mux.NewRouter()
	router.NewRoute().
		Name("/leo.example.path.v1.Path/BoolPath").
		Methods("GET").
		Path("/v1/{bool}/{opt_bool}/{wrap_bool}")
	router.NewRoute().
		Name("/leo.example.path.v1.Path/Int32Path").
		Methods("GET").
		Path("/v1/{int32}/{sint32}/{sfixed32}/{opt_int32}/{opt_sint32}/{opt_sfixed32}/{wrap_int32}")
	router.NewRoute().
		Name("/leo.example.path.v1.Path/Int64Path").
		Methods("GET").
		Path("/v1/{int64}/{sint64}/{sfixed64}/{opt_int64}/{opt_sint64}/{opt_sfixed64}/{wrap_int64}")
	router.NewRoute().
		Name("/leo.example.path.v1.Path/Uint32Path").
		Methods("GET").
		Path("/v1/{uint32}/{fixed32}/{opt_uint32}/{opt_fixed32}/{wrap_uint32}")
	router.NewRoute().
		Name("/leo.example.path.v1.Path/Uint64Path").
		Methods("GET").
		Path("/v1/{uint64}/{fixed64}/{opt_uint64}/{opt_fixed64}/{wrap_uint64}")
	router.NewRoute().
		Name("/leo.example.path.v1.Path/FloatPath").
		Methods("GET").
		Path("/v1/{float}/{opt_float}/{wrap_float}")
	router.NewRoute().
		Name("/leo.example.path.v1.Path/DoublePath").
		Methods("GET").
		Path("/v1/{double}/{opt_double}/{wrap_double}")
	router.NewRoute().
		Name("/leo.example.path.v1.Path/StringPath").
		Methods("GET").
		Path("/v1/{string}/{opt_string}/{wrap_string}")
	router.NewRoute().
		Name("/leo.example.path.v1.Path/EnumPath").
		Methods("GET").
		Path("/v1/{status}/{opt_status}")
	return &pathHTTPClient{
		boolPath: endpointx.Chain(
			http.NewExplicitClient(
				func(ctx context.Context, obj interface{}) (*http1.Request, error) {
					if obj == nil {
						return nil, errors.New("request object is nil")
					}
					req, ok := obj.(*PathRequest)
					if !ok {
						return nil, fmt.Errorf("invalid request object type, %T", obj)
					}
					_ = req
					var body io.Reader
					var pairs []string
					pairs = append(pairs, "bool", strconv.FormatBool(req.GetBool()), "opt_bool", strconv.FormatBool(req.GetOptBool()), "wrap_bool", strconv.FormatBool(req.GetWrapBool().GetValue()))
					path, err := router.Get("/leo.example.path.v1.Path/BoolPath").URLPath(pairs...)
					if err != nil {
						return nil, err
					}
					queries := url.Values{}
					queries.Add("int32", strconv.FormatInt(int64(req.GetInt32()), 10))
					queries.Add("sint32", strconv.FormatInt(int64(req.GetSint32()), 10))
					queries.Add("sfixed32", strconv.FormatInt(int64(req.GetSfixed32()), 10))
					queries.Add("opt_int32", strconv.FormatInt(int64(req.GetOptInt32()), 10))
					queries.Add("opt_sint32", strconv.FormatInt(int64(req.GetOptSint32()), 10))
					queries.Add("opt_sfixed32", strconv.FormatInt(int64(req.GetOptSfixed32()), 10))
					queries.Add("wrap_int32", strconv.FormatInt(int64(req.GetWrapInt32().GetValue()), 10))
					queries.Add("int64", strconv.FormatInt(req.GetInt64(), 10))
					queries.Add("sint64", strconv.FormatInt(req.GetSint64(), 10))
					queries.Add("sfixed64", strconv.FormatInt(req.GetSfixed64(), 10))
					queries.Add("opt_int64", strconv.FormatInt(req.GetOptInt64(), 10))
					queries.Add("opt_sint64", strconv.FormatInt(req.GetOptSint64(), 10))
					queries.Add("opt_sfixed64", strconv.FormatInt(req.GetOptSfixed64(), 10))
					queries.Add("wrap_int64", strconv.FormatInt(req.GetWrapInt64().GetValue(), 10))
					queries.Add("uint32", strconv.FormatUint(uint64(req.GetUint32()), 10))
					queries.Add("fixed32", strconv.FormatUint(uint64(req.GetFixed32()), 10))
					queries.Add("opt_uint32", strconv.FormatUint(uint64(req.GetOptUint32()), 10))
					queries.Add("opt_fixed32", strconv.FormatUint(uint64(req.GetOptFixed32()), 10))
					queries.Add("wrap_uint32", strconv.FormatUint(uint64(req.GetWrapUint32().GetValue()), 10))
					queries.Add("uint64", strconv.FormatUint(req.GetUint64(), 10))
					queries.Add("fixed64", strconv.FormatUint(req.GetFixed64(), 10))
					queries.Add("opt_uint64", strconv.FormatUint(req.GetOptUint64(), 10))
					queries.Add("opt_fixed64", strconv.FormatUint(req.GetOptFixed64(), 10))
					queries.Add("wrap_uint64", strconv.FormatUint(req.GetWrapUint64().GetValue(), 10))
					queries.Add("float", strconv.FormatFloat(float64(req.GetFloat()), 'f', -1, 32))
					queries.Add("opt_float", strconv.FormatFloat(float64(req.GetOptFloat()), 'f', -1, 32))
					queries.Add("wrap_float", strconv.FormatFloat(float64(req.GetWrapFloat().GetValue()), 'f', -1, 32))
					queries.Add("double", strconv.FormatFloat(req.GetDouble(), 'f', -1, 64))
					queries.Add("opt_double", strconv.FormatFloat(req.GetOptDouble(), 'f', -1, 64))
					queries.Add("wrap_double", strconv.FormatFloat(req.GetWrapDouble().GetValue(), 'f', -1, 64))
					queries.Add("string", req.GetString_())
					queries.Add("opt_string", req.GetOptString())
					queries.Add("wrap_string", req.GetWrapString().GetValue())
					queries.Add("status", strconv.FormatInt(int64(req.GetStatus()), 10))
					queries.Add("opt_status", strconv.FormatInt(int64(req.GetOptStatus()), 10))
					target := &url.URL{
						Scheme:   scheme,
						Host:     instance,
						Path:     path.Path,
						RawQuery: queries.Encode(),
					}
					r, err := http1.NewRequestWithContext(ctx, "GET", target.String(), body)
					if err != nil {
						return nil, err
					}
					return r, nil
				},
				func(ctx context.Context, r *http1.Response) (interface{}, error) {
					return nil, nil
				},
				opts...,
			).Endpoint(),
			mdw...),
		int32Path: endpointx.Chain(
			http.NewExplicitClient(
				func(ctx context.Context, obj interface{}) (*http1.Request, error) {
					if obj == nil {
						return nil, errors.New("request object is nil")
					}
					req, ok := obj.(*PathRequest)
					if !ok {
						return nil, fmt.Errorf("invalid request object type, %T", obj)
					}
					_ = req
					var body io.Reader
					var pairs []string
					pairs = append(pairs, "int32", strconv.FormatInt(int64(req.GetInt32()), 10), "sint32", strconv.FormatInt(int64(req.GetSint32()), 10), "sfixed32", strconv.FormatInt(int64(req.GetSfixed32()), 10), "opt_int32", strconv.FormatInt(int64(req.GetOptInt32()), 10), "opt_sint32", strconv.FormatInt(int64(req.GetOptSint32()), 10), "opt_sfixed32", strconv.FormatInt(int64(req.GetOptSfixed32()), 10), "wrap_int32", strconv.FormatInt(int64(req.GetWrapInt32().GetValue()), 10))
					path, err := router.Get("/leo.example.path.v1.Path/Int32Path").URLPath(pairs...)
					if err != nil {
						return nil, err
					}
					queries := url.Values{}
					queries.Add("bool", strconv.FormatBool(req.GetBool()))
					queries.Add("opt_bool", strconv.FormatBool(req.GetOptBool()))
					queries.Add("wrap_bool", strconv.FormatBool(req.GetWrapBool().GetValue()))
					queries.Add("int64", strconv.FormatInt(req.GetInt64(), 10))
					queries.Add("sint64", strconv.FormatInt(req.GetSint64(), 10))
					queries.Add("sfixed64", strconv.FormatInt(req.GetSfixed64(), 10))
					queries.Add("opt_int64", strconv.FormatInt(req.GetOptInt64(), 10))
					queries.Add("opt_sint64", strconv.FormatInt(req.GetOptSint64(), 10))
					queries.Add("opt_sfixed64", strconv.FormatInt(req.GetOptSfixed64(), 10))
					queries.Add("wrap_int64", strconv.FormatInt(req.GetWrapInt64().GetValue(), 10))
					queries.Add("uint32", strconv.FormatUint(uint64(req.GetUint32()), 10))
					queries.Add("fixed32", strconv.FormatUint(uint64(req.GetFixed32()), 10))
					queries.Add("opt_uint32", strconv.FormatUint(uint64(req.GetOptUint32()), 10))
					queries.Add("opt_fixed32", strconv.FormatUint(uint64(req.GetOptFixed32()), 10))
					queries.Add("wrap_uint32", strconv.FormatUint(uint64(req.GetWrapUint32().GetValue()), 10))
					queries.Add("uint64", strconv.FormatUint(req.GetUint64(), 10))
					queries.Add("fixed64", strconv.FormatUint(req.GetFixed64(), 10))
					queries.Add("opt_uint64", strconv.FormatUint(req.GetOptUint64(), 10))
					queries.Add("opt_fixed64", strconv.FormatUint(req.GetOptFixed64(), 10))
					queries.Add("wrap_uint64", strconv.FormatUint(req.GetWrapUint64().GetValue(), 10))
					queries.Add("float", strconv.FormatFloat(float64(req.GetFloat()), 'f', -1, 32))
					queries.Add("opt_float", strconv.FormatFloat(float64(req.GetOptFloat()), 'f', -1, 32))
					queries.Add("wrap_float", strconv.FormatFloat(float64(req.GetWrapFloat().GetValue()), 'f', -1, 32))
					queries.Add("double", strconv.FormatFloat(req.GetDouble(), 'f', -1, 64))
					queries.Add("opt_double", strconv.FormatFloat(req.GetOptDouble(), 'f', -1, 64))
					queries.Add("wrap_double", strconv.FormatFloat(req.GetWrapDouble().GetValue(), 'f', -1, 64))
					queries.Add("string", req.GetString_())
					queries.Add("opt_string", req.GetOptString())
					queries.Add("wrap_string", req.GetWrapString().GetValue())
					queries.Add("status", strconv.FormatInt(int64(req.GetStatus()), 10))
					queries.Add("opt_status", strconv.FormatInt(int64(req.GetOptStatus()), 10))
					target := &url.URL{
						Scheme:   scheme,
						Host:     instance,
						Path:     path.Path,
						RawQuery: queries.Encode(),
					}
					r, err := http1.NewRequestWithContext(ctx, "GET", target.String(), body)
					if err != nil {
						return nil, err
					}
					return r, nil
				},
				func(ctx context.Context, r *http1.Response) (interface{}, error) {
					return nil, nil
				},
				opts...,
			).Endpoint(),
			mdw...),
		int64Path: endpointx.Chain(
			http.NewExplicitClient(
				func(ctx context.Context, obj interface{}) (*http1.Request, error) {
					if obj == nil {
						return nil, errors.New("request object is nil")
					}
					req, ok := obj.(*PathRequest)
					if !ok {
						return nil, fmt.Errorf("invalid request object type, %T", obj)
					}
					_ = req
					var body io.Reader
					var pairs []string
					pairs = append(pairs, "int64", strconv.FormatInt(req.GetInt64(), 10), "sint64", strconv.FormatInt(req.GetSint64(), 10), "sfixed64", strconv.FormatInt(req.GetSfixed64(), 10), "opt_int64", strconv.FormatInt(req.GetOptInt64(), 10), "opt_sint64", strconv.FormatInt(req.GetOptSint64(), 10), "opt_sfixed64", strconv.FormatInt(req.GetOptSfixed64(), 10), "wrap_int64", strconv.FormatInt(req.GetWrapInt64().GetValue(), 10))
					path, err := router.Get("/leo.example.path.v1.Path/Int64Path").URLPath(pairs...)
					if err != nil {
						return nil, err
					}
					queries := url.Values{}
					queries.Add("bool", strconv.FormatBool(req.GetBool()))
					queries.Add("opt_bool", strconv.FormatBool(req.GetOptBool()))
					queries.Add("wrap_bool", strconv.FormatBool(req.GetWrapBool().GetValue()))
					queries.Add("int32", strconv.FormatInt(int64(req.GetInt32()), 10))
					queries.Add("sint32", strconv.FormatInt(int64(req.GetSint32()), 10))
					queries.Add("sfixed32", strconv.FormatInt(int64(req.GetSfixed32()), 10))
					queries.Add("opt_int32", strconv.FormatInt(int64(req.GetOptInt32()), 10))
					queries.Add("opt_sint32", strconv.FormatInt(int64(req.GetOptSint32()), 10))
					queries.Add("opt_sfixed32", strconv.FormatInt(int64(req.GetOptSfixed32()), 10))
					queries.Add("wrap_int32", strconv.FormatInt(int64(req.GetWrapInt32().GetValue()), 10))
					queries.Add("uint32", strconv.FormatUint(uint64(req.GetUint32()), 10))
					queries.Add("fixed32", strconv.FormatUint(uint64(req.GetFixed32()), 10))
					queries.Add("opt_uint32", strconv.FormatUint(uint64(req.GetOptUint32()), 10))
					queries.Add("opt_fixed32", strconv.FormatUint(uint64(req.GetOptFixed32()), 10))
					queries.Add("wrap_uint32", strconv.FormatUint(uint64(req.GetWrapUint32().GetValue()), 10))
					queries.Add("uint64", strconv.FormatUint(req.GetUint64(), 10))
					queries.Add("fixed64", strconv.FormatUint(req.GetFixed64(), 10))
					queries.Add("opt_uint64", strconv.FormatUint(req.GetOptUint64(), 10))
					queries.Add("opt_fixed64", strconv.FormatUint(req.GetOptFixed64(), 10))
					queries.Add("wrap_uint64", strconv.FormatUint(req.GetWrapUint64().GetValue(), 10))
					queries.Add("float", strconv.FormatFloat(float64(req.GetFloat()), 'f', -1, 32))
					queries.Add("opt_float", strconv.FormatFloat(float64(req.GetOptFloat()), 'f', -1, 32))
					queries.Add("wrap_float", strconv.FormatFloat(float64(req.GetWrapFloat().GetValue()), 'f', -1, 32))
					queries.Add("double", strconv.FormatFloat(req.GetDouble(), 'f', -1, 64))
					queries.Add("opt_double", strconv.FormatFloat(req.GetOptDouble(), 'f', -1, 64))
					queries.Add("wrap_double", strconv.FormatFloat(req.GetWrapDouble().GetValue(), 'f', -1, 64))
					queries.Add("string", req.GetString_())
					queries.Add("opt_string", req.GetOptString())
					queries.Add("wrap_string", req.GetWrapString().GetValue())
					queries.Add("status", strconv.FormatInt(int64(req.GetStatus()), 10))
					queries.Add("opt_status", strconv.FormatInt(int64(req.GetOptStatus()), 10))
					target := &url.URL{
						Scheme:   scheme,
						Host:     instance,
						Path:     path.Path,
						RawQuery: queries.Encode(),
					}
					r, err := http1.NewRequestWithContext(ctx, "GET", target.String(), body)
					if err != nil {
						return nil, err
					}
					return r, nil
				},
				func(ctx context.Context, r *http1.Response) (interface{}, error) {
					return nil, nil
				},
				opts...,
			).Endpoint(),
			mdw...),
		uint32Path: endpointx.Chain(
			http.NewExplicitClient(
				func(ctx context.Context, obj interface{}) (*http1.Request, error) {
					if obj == nil {
						return nil, errors.New("request object is nil")
					}
					req, ok := obj.(*PathRequest)
					if !ok {
						return nil, fmt.Errorf("invalid request object type, %T", obj)
					}
					_ = req
					var body io.Reader
					var pairs []string
					pairs = append(pairs, "uint32", strconv.FormatUint(uint64(req.GetUint32()), 10), "fixed32", strconv.FormatUint(uint64(req.GetFixed32()), 10), "opt_uint32", strconv.FormatUint(uint64(req.GetOptUint32()), 10), "opt_fixed32", strconv.FormatUint(uint64(req.GetOptFixed32()), 10), "wrap_uint32", strconv.FormatUint(uint64(req.GetWrapUint32().GetValue()), 10))
					path, err := router.Get("/leo.example.path.v1.Path/Uint32Path").URLPath(pairs...)
					if err != nil {
						return nil, err
					}
					queries := url.Values{}
					queries.Add("bool", strconv.FormatBool(req.GetBool()))
					queries.Add("opt_bool", strconv.FormatBool(req.GetOptBool()))
					queries.Add("wrap_bool", strconv.FormatBool(req.GetWrapBool().GetValue()))
					queries.Add("int32", strconv.FormatInt(int64(req.GetInt32()), 10))
					queries.Add("sint32", strconv.FormatInt(int64(req.GetSint32()), 10))
					queries.Add("sfixed32", strconv.FormatInt(int64(req.GetSfixed32()), 10))
					queries.Add("opt_int32", strconv.FormatInt(int64(req.GetOptInt32()), 10))
					queries.Add("opt_sint32", strconv.FormatInt(int64(req.GetOptSint32()), 10))
					queries.Add("opt_sfixed32", strconv.FormatInt(int64(req.GetOptSfixed32()), 10))
					queries.Add("wrap_int32", strconv.FormatInt(int64(req.GetWrapInt32().GetValue()), 10))
					queries.Add("int64", strconv.FormatInt(req.GetInt64(), 10))
					queries.Add("sint64", strconv.FormatInt(req.GetSint64(), 10))
					queries.Add("sfixed64", strconv.FormatInt(req.GetSfixed64(), 10))
					queries.Add("opt_int64", strconv.FormatInt(req.GetOptInt64(), 10))
					queries.Add("opt_sint64", strconv.FormatInt(req.GetOptSint64(), 10))
					queries.Add("opt_sfixed64", strconv.FormatInt(req.GetOptSfixed64(), 10))
					queries.Add("wrap_int64", strconv.FormatInt(req.GetWrapInt64().GetValue(), 10))
					queries.Add("uint64", strconv.FormatUint(req.GetUint64(), 10))
					queries.Add("fixed64", strconv.FormatUint(req.GetFixed64(), 10))
					queries.Add("opt_uint64", strconv.FormatUint(req.GetOptUint64(), 10))
					queries.Add("opt_fixed64", strconv.FormatUint(req.GetOptFixed64(), 10))
					queries.Add("wrap_uint64", strconv.FormatUint(req.GetWrapUint64().GetValue(), 10))
					queries.Add("float", strconv.FormatFloat(float64(req.GetFloat()), 'f', -1, 32))
					queries.Add("opt_float", strconv.FormatFloat(float64(req.GetOptFloat()), 'f', -1, 32))
					queries.Add("wrap_float", strconv.FormatFloat(float64(req.GetWrapFloat().GetValue()), 'f', -1, 32))
					queries.Add("double", strconv.FormatFloat(req.GetDouble(), 'f', -1, 64))
					queries.Add("opt_double", strconv.FormatFloat(req.GetOptDouble(), 'f', -1, 64))
					queries.Add("wrap_double", strconv.FormatFloat(req.GetWrapDouble().GetValue(), 'f', -1, 64))
					queries.Add("string", req.GetString_())
					queries.Add("opt_string", req.GetOptString())
					queries.Add("wrap_string", req.GetWrapString().GetValue())
					queries.Add("status", strconv.FormatInt(int64(req.GetStatus()), 10))
					queries.Add("opt_status", strconv.FormatInt(int64(req.GetOptStatus()), 10))
					target := &url.URL{
						Scheme:   scheme,
						Host:     instance,
						Path:     path.Path,
						RawQuery: queries.Encode(),
					}
					r, err := http1.NewRequestWithContext(ctx, "GET", target.String(), body)
					if err != nil {
						return nil, err
					}
					return r, nil
				},
				func(ctx context.Context, r *http1.Response) (interface{}, error) {
					return nil, nil
				},
				opts...,
			).Endpoint(),
			mdw...),
		uint64Path: endpointx.Chain(
			http.NewExplicitClient(
				func(ctx context.Context, obj interface{}) (*http1.Request, error) {
					if obj == nil {
						return nil, errors.New("request object is nil")
					}
					req, ok := obj.(*PathRequest)
					if !ok {
						return nil, fmt.Errorf("invalid request object type, %T", obj)
					}
					_ = req
					var body io.Reader
					var pairs []string
					pairs = append(pairs, "uint64", strconv.FormatUint(req.GetUint64(), 10), "fixed64", strconv.FormatUint(req.GetFixed64(), 10), "opt_uint64", strconv.FormatUint(req.GetOptUint64(), 10), "opt_fixed64", strconv.FormatUint(req.GetOptFixed64(), 10), "wrap_uint64", strconv.FormatUint(req.GetWrapUint64().GetValue(), 10))
					path, err := router.Get("/leo.example.path.v1.Path/Uint64Path").URLPath(pairs...)
					if err != nil {
						return nil, err
					}
					queries := url.Values{}
					queries.Add("bool", strconv.FormatBool(req.GetBool()))
					queries.Add("opt_bool", strconv.FormatBool(req.GetOptBool()))
					queries.Add("wrap_bool", strconv.FormatBool(req.GetWrapBool().GetValue()))
					queries.Add("int32", strconv.FormatInt(int64(req.GetInt32()), 10))
					queries.Add("sint32", strconv.FormatInt(int64(req.GetSint32()), 10))
					queries.Add("sfixed32", strconv.FormatInt(int64(req.GetSfixed32()), 10))
					queries.Add("opt_int32", strconv.FormatInt(int64(req.GetOptInt32()), 10))
					queries.Add("opt_sint32", strconv.FormatInt(int64(req.GetOptSint32()), 10))
					queries.Add("opt_sfixed32", strconv.FormatInt(int64(req.GetOptSfixed32()), 10))
					queries.Add("wrap_int32", strconv.FormatInt(int64(req.GetWrapInt32().GetValue()), 10))
					queries.Add("int64", strconv.FormatInt(req.GetInt64(), 10))
					queries.Add("sint64", strconv.FormatInt(req.GetSint64(), 10))
					queries.Add("sfixed64", strconv.FormatInt(req.GetSfixed64(), 10))
					queries.Add("opt_int64", strconv.FormatInt(req.GetOptInt64(), 10))
					queries.Add("opt_sint64", strconv.FormatInt(req.GetOptSint64(), 10))
					queries.Add("opt_sfixed64", strconv.FormatInt(req.GetOptSfixed64(), 10))
					queries.Add("wrap_int64", strconv.FormatInt(req.GetWrapInt64().GetValue(), 10))
					queries.Add("uint32", strconv.FormatUint(uint64(req.GetUint32()), 10))
					queries.Add("fixed32", strconv.FormatUint(uint64(req.GetFixed32()), 10))
					queries.Add("opt_uint32", strconv.FormatUint(uint64(req.GetOptUint32()), 10))
					queries.Add("opt_fixed32", strconv.FormatUint(uint64(req.GetOptFixed32()), 10))
					queries.Add("wrap_uint32", strconv.FormatUint(uint64(req.GetWrapUint32().GetValue()), 10))
					queries.Add("float", strconv.FormatFloat(float64(req.GetFloat()), 'f', -1, 32))
					queries.Add("opt_float", strconv.FormatFloat(float64(req.GetOptFloat()), 'f', -1, 32))
					queries.Add("wrap_float", strconv.FormatFloat(float64(req.GetWrapFloat().GetValue()), 'f', -1, 32))
					queries.Add("double", strconv.FormatFloat(req.GetDouble(), 'f', -1, 64))
					queries.Add("opt_double", strconv.FormatFloat(req.GetOptDouble(), 'f', -1, 64))
					queries.Add("wrap_double", strconv.FormatFloat(req.GetWrapDouble().GetValue(), 'f', -1, 64))
					queries.Add("string", req.GetString_())
					queries.Add("opt_string", req.GetOptString())
					queries.Add("wrap_string", req.GetWrapString().GetValue())
					queries.Add("status", strconv.FormatInt(int64(req.GetStatus()), 10))
					queries.Add("opt_status", strconv.FormatInt(int64(req.GetOptStatus()), 10))
					target := &url.URL{
						Scheme:   scheme,
						Host:     instance,
						Path:     path.Path,
						RawQuery: queries.Encode(),
					}
					r, err := http1.NewRequestWithContext(ctx, "GET", target.String(), body)
					if err != nil {
						return nil, err
					}
					return r, nil
				},
				func(ctx context.Context, r *http1.Response) (interface{}, error) {
					return nil, nil
				},
				opts...,
			).Endpoint(),
			mdw...),
		floatPath: endpointx.Chain(
			http.NewExplicitClient(
				func(ctx context.Context, obj interface{}) (*http1.Request, error) {
					if obj == nil {
						return nil, errors.New("request object is nil")
					}
					req, ok := obj.(*PathRequest)
					if !ok {
						return nil, fmt.Errorf("invalid request object type, %T", obj)
					}
					_ = req
					var body io.Reader
					var pairs []string
					pairs = append(pairs, "float", strconv.FormatFloat(float64(req.GetFloat()), 'f', -1, 32), "opt_float", strconv.FormatFloat(float64(req.GetOptFloat()), 'f', -1, 32), "wrap_float", strconv.FormatFloat(float64(req.GetWrapFloat().GetValue()), 'f', -1, 32))
					path, err := router.Get("/leo.example.path.v1.Path/FloatPath").URLPath(pairs...)
					if err != nil {
						return nil, err
					}
					queries := url.Values{}
					queries.Add("bool", strconv.FormatBool(req.GetBool()))
					queries.Add("opt_bool", strconv.FormatBool(req.GetOptBool()))
					queries.Add("wrap_bool", strconv.FormatBool(req.GetWrapBool().GetValue()))
					queries.Add("int32", strconv.FormatInt(int64(req.GetInt32()), 10))
					queries.Add("sint32", strconv.FormatInt(int64(req.GetSint32()), 10))
					queries.Add("sfixed32", strconv.FormatInt(int64(req.GetSfixed32()), 10))
					queries.Add("opt_int32", strconv.FormatInt(int64(req.GetOptInt32()), 10))
					queries.Add("opt_sint32", strconv.FormatInt(int64(req.GetOptSint32()), 10))
					queries.Add("opt_sfixed32", strconv.FormatInt(int64(req.GetOptSfixed32()), 10))
					queries.Add("wrap_int32", strconv.FormatInt(int64(req.GetWrapInt32().GetValue()), 10))
					queries.Add("int64", strconv.FormatInt(req.GetInt64(), 10))
					queries.Add("sint64", strconv.FormatInt(req.GetSint64(), 10))
					queries.Add("sfixed64", strconv.FormatInt(req.GetSfixed64(), 10))
					queries.Add("opt_int64", strconv.FormatInt(req.GetOptInt64(), 10))
					queries.Add("opt_sint64", strconv.FormatInt(req.GetOptSint64(), 10))
					queries.Add("opt_sfixed64", strconv.FormatInt(req.GetOptSfixed64(), 10))
					queries.Add("wrap_int64", strconv.FormatInt(req.GetWrapInt64().GetValue(), 10))
					queries.Add("uint32", strconv.FormatUint(uint64(req.GetUint32()), 10))
					queries.Add("fixed32", strconv.FormatUint(uint64(req.GetFixed32()), 10))
					queries.Add("opt_uint32", strconv.FormatUint(uint64(req.GetOptUint32()), 10))
					queries.Add("opt_fixed32", strconv.FormatUint(uint64(req.GetOptFixed32()), 10))
					queries.Add("wrap_uint32", strconv.FormatUint(uint64(req.GetWrapUint32().GetValue()), 10))
					queries.Add("uint64", strconv.FormatUint(req.GetUint64(), 10))
					queries.Add("fixed64", strconv.FormatUint(req.GetFixed64(), 10))
					queries.Add("opt_uint64", strconv.FormatUint(req.GetOptUint64(), 10))
					queries.Add("opt_fixed64", strconv.FormatUint(req.GetOptFixed64(), 10))
					queries.Add("wrap_uint64", strconv.FormatUint(req.GetWrapUint64().GetValue(), 10))
					queries.Add("double", strconv.FormatFloat(req.GetDouble(), 'f', -1, 64))
					queries.Add("opt_double", strconv.FormatFloat(req.GetOptDouble(), 'f', -1, 64))
					queries.Add("wrap_double", strconv.FormatFloat(req.GetWrapDouble().GetValue(), 'f', -1, 64))
					queries.Add("string", req.GetString_())
					queries.Add("opt_string", req.GetOptString())
					queries.Add("wrap_string", req.GetWrapString().GetValue())
					queries.Add("status", strconv.FormatInt(int64(req.GetStatus()), 10))
					queries.Add("opt_status", strconv.FormatInt(int64(req.GetOptStatus()), 10))
					target := &url.URL{
						Scheme:   scheme,
						Host:     instance,
						Path:     path.Path,
						RawQuery: queries.Encode(),
					}
					r, err := http1.NewRequestWithContext(ctx, "GET", target.String(), body)
					if err != nil {
						return nil, err
					}
					return r, nil
				},
				func(ctx context.Context, r *http1.Response) (interface{}, error) {
					return nil, nil
				},
				opts...,
			).Endpoint(),
			mdw...),
		doublePath: endpointx.Chain(
			http.NewExplicitClient(
				func(ctx context.Context, obj interface{}) (*http1.Request, error) {
					if obj == nil {
						return nil, errors.New("request object is nil")
					}
					req, ok := obj.(*PathRequest)
					if !ok {
						return nil, fmt.Errorf("invalid request object type, %T", obj)
					}
					_ = req
					var body io.Reader
					var pairs []string
					pairs = append(pairs, "double", strconv.FormatFloat(req.GetDouble(), 'f', -1, 64), "opt_double", strconv.FormatFloat(req.GetOptDouble(), 'f', -1, 64), "wrap_double", strconv.FormatFloat(req.GetWrapDouble().GetValue(), 'f', -1, 64))
					path, err := router.Get("/leo.example.path.v1.Path/DoublePath").URLPath(pairs...)
					if err != nil {
						return nil, err
					}
					queries := url.Values{}
					queries.Add("bool", strconv.FormatBool(req.GetBool()))
					queries.Add("opt_bool", strconv.FormatBool(req.GetOptBool()))
					queries.Add("wrap_bool", strconv.FormatBool(req.GetWrapBool().GetValue()))
					queries.Add("int32", strconv.FormatInt(int64(req.GetInt32()), 10))
					queries.Add("sint32", strconv.FormatInt(int64(req.GetSint32()), 10))
					queries.Add("sfixed32", strconv.FormatInt(int64(req.GetSfixed32()), 10))
					queries.Add("opt_int32", strconv.FormatInt(int64(req.GetOptInt32()), 10))
					queries.Add("opt_sint32", strconv.FormatInt(int64(req.GetOptSint32()), 10))
					queries.Add("opt_sfixed32", strconv.FormatInt(int64(req.GetOptSfixed32()), 10))
					queries.Add("wrap_int32", strconv.FormatInt(int64(req.GetWrapInt32().GetValue()), 10))
					queries.Add("int64", strconv.FormatInt(req.GetInt64(), 10))
					queries.Add("sint64", strconv.FormatInt(req.GetSint64(), 10))
					queries.Add("sfixed64", strconv.FormatInt(req.GetSfixed64(), 10))
					queries.Add("opt_int64", strconv.FormatInt(req.GetOptInt64(), 10))
					queries.Add("opt_sint64", strconv.FormatInt(req.GetOptSint64(), 10))
					queries.Add("opt_sfixed64", strconv.FormatInt(req.GetOptSfixed64(), 10))
					queries.Add("wrap_int64", strconv.FormatInt(req.GetWrapInt64().GetValue(), 10))
					queries.Add("uint32", strconv.FormatUint(uint64(req.GetUint32()), 10))
					queries.Add("fixed32", strconv.FormatUint(uint64(req.GetFixed32()), 10))
					queries.Add("opt_uint32", strconv.FormatUint(uint64(req.GetOptUint32()), 10))
					queries.Add("opt_fixed32", strconv.FormatUint(uint64(req.GetOptFixed32()), 10))
					queries.Add("wrap_uint32", strconv.FormatUint(uint64(req.GetWrapUint32().GetValue()), 10))
					queries.Add("uint64", strconv.FormatUint(req.GetUint64(), 10))
					queries.Add("fixed64", strconv.FormatUint(req.GetFixed64(), 10))
					queries.Add("opt_uint64", strconv.FormatUint(req.GetOptUint64(), 10))
					queries.Add("opt_fixed64", strconv.FormatUint(req.GetOptFixed64(), 10))
					queries.Add("wrap_uint64", strconv.FormatUint(req.GetWrapUint64().GetValue(), 10))
					queries.Add("float", strconv.FormatFloat(float64(req.GetFloat()), 'f', -1, 32))
					queries.Add("opt_float", strconv.FormatFloat(float64(req.GetOptFloat()), 'f', -1, 32))
					queries.Add("wrap_float", strconv.FormatFloat(float64(req.GetWrapFloat().GetValue()), 'f', -1, 32))
					queries.Add("string", req.GetString_())
					queries.Add("opt_string", req.GetOptString())
					queries.Add("wrap_string", req.GetWrapString().GetValue())
					queries.Add("status", strconv.FormatInt(int64(req.GetStatus()), 10))
					queries.Add("opt_status", strconv.FormatInt(int64(req.GetOptStatus()), 10))
					target := &url.URL{
						Scheme:   scheme,
						Host:     instance,
						Path:     path.Path,
						RawQuery: queries.Encode(),
					}
					r, err := http1.NewRequestWithContext(ctx, "GET", target.String(), body)
					if err != nil {
						return nil, err
					}
					return r, nil
				},
				func(ctx context.Context, r *http1.Response) (interface{}, error) {
					return nil, nil
				},
				opts...,
			).Endpoint(),
			mdw...),
		stringPath: endpointx.Chain(
			http.NewExplicitClient(
				func(ctx context.Context, obj interface{}) (*http1.Request, error) {
					if obj == nil {
						return nil, errors.New("request object is nil")
					}
					req, ok := obj.(*PathRequest)
					if !ok {
						return nil, fmt.Errorf("invalid request object type, %T", obj)
					}
					_ = req
					var body io.Reader
					var pairs []string
					pairs = append(pairs, "string", req.GetString_(), "opt_string", req.GetOptString(), "wrap_string", req.GetWrapString().GetValue())
					path, err := router.Get("/leo.example.path.v1.Path/StringPath").URLPath(pairs...)
					if err != nil {
						return nil, err
					}
					queries := url.Values{}
					queries.Add("bool", strconv.FormatBool(req.GetBool()))
					queries.Add("opt_bool", strconv.FormatBool(req.GetOptBool()))
					queries.Add("wrap_bool", strconv.FormatBool(req.GetWrapBool().GetValue()))
					queries.Add("int32", strconv.FormatInt(int64(req.GetInt32()), 10))
					queries.Add("sint32", strconv.FormatInt(int64(req.GetSint32()), 10))
					queries.Add("sfixed32", strconv.FormatInt(int64(req.GetSfixed32()), 10))
					queries.Add("opt_int32", strconv.FormatInt(int64(req.GetOptInt32()), 10))
					queries.Add("opt_sint32", strconv.FormatInt(int64(req.GetOptSint32()), 10))
					queries.Add("opt_sfixed32", strconv.FormatInt(int64(req.GetOptSfixed32()), 10))
					queries.Add("wrap_int32", strconv.FormatInt(int64(req.GetWrapInt32().GetValue()), 10))
					queries.Add("int64", strconv.FormatInt(req.GetInt64(), 10))
					queries.Add("sint64", strconv.FormatInt(req.GetSint64(), 10))
					queries.Add("sfixed64", strconv.FormatInt(req.GetSfixed64(), 10))
					queries.Add("opt_int64", strconv.FormatInt(req.GetOptInt64(), 10))
					queries.Add("opt_sint64", strconv.FormatInt(req.GetOptSint64(), 10))
					queries.Add("opt_sfixed64", strconv.FormatInt(req.GetOptSfixed64(), 10))
					queries.Add("wrap_int64", strconv.FormatInt(req.GetWrapInt64().GetValue(), 10))
					queries.Add("uint32", strconv.FormatUint(uint64(req.GetUint32()), 10))
					queries.Add("fixed32", strconv.FormatUint(uint64(req.GetFixed32()), 10))
					queries.Add("opt_uint32", strconv.FormatUint(uint64(req.GetOptUint32()), 10))
					queries.Add("opt_fixed32", strconv.FormatUint(uint64(req.GetOptFixed32()), 10))
					queries.Add("wrap_uint32", strconv.FormatUint(uint64(req.GetWrapUint32().GetValue()), 10))
					queries.Add("uint64", strconv.FormatUint(req.GetUint64(), 10))
					queries.Add("fixed64", strconv.FormatUint(req.GetFixed64(), 10))
					queries.Add("opt_uint64", strconv.FormatUint(req.GetOptUint64(), 10))
					queries.Add("opt_fixed64", strconv.FormatUint(req.GetOptFixed64(), 10))
					queries.Add("wrap_uint64", strconv.FormatUint(req.GetWrapUint64().GetValue(), 10))
					queries.Add("float", strconv.FormatFloat(float64(req.GetFloat()), 'f', -1, 32))
					queries.Add("opt_float", strconv.FormatFloat(float64(req.GetOptFloat()), 'f', -1, 32))
					queries.Add("wrap_float", strconv.FormatFloat(float64(req.GetWrapFloat().GetValue()), 'f', -1, 32))
					queries.Add("double", strconv.FormatFloat(req.GetDouble(), 'f', -1, 64))
					queries.Add("opt_double", strconv.FormatFloat(req.GetOptDouble(), 'f', -1, 64))
					queries.Add("wrap_double", strconv.FormatFloat(req.GetWrapDouble().GetValue(), 'f', -1, 64))
					queries.Add("status", strconv.FormatInt(int64(req.GetStatus()), 10))
					queries.Add("opt_status", strconv.FormatInt(int64(req.GetOptStatus()), 10))
					target := &url.URL{
						Scheme:   scheme,
						Host:     instance,
						Path:     path.Path,
						RawQuery: queries.Encode(),
					}
					r, err := http1.NewRequestWithContext(ctx, "GET", target.String(), body)
					if err != nil {
						return nil, err
					}
					return r, nil
				},
				func(ctx context.Context, r *http1.Response) (interface{}, error) {
					return nil, nil
				},
				opts...,
			).Endpoint(),
			mdw...),
		enumPath: endpointx.Chain(
			http.NewExplicitClient(
				func(ctx context.Context, obj interface{}) (*http1.Request, error) {
					if obj == nil {
						return nil, errors.New("request object is nil")
					}
					req, ok := obj.(*PathRequest)
					if !ok {
						return nil, fmt.Errorf("invalid request object type, %T", obj)
					}
					_ = req
					var body io.Reader
					var pairs []string
					pairs = append(pairs, "status", strconv.FormatInt(int64(req.GetStatus()), 10), "opt_status", strconv.FormatInt(int64(req.GetOptStatus()), 10))
					path, err := router.Get("/leo.example.path.v1.Path/EnumPath").URLPath(pairs...)
					if err != nil {
						return nil, err
					}
					queries := url.Values{}
					queries.Add("bool", strconv.FormatBool(req.GetBool()))
					queries.Add("opt_bool", strconv.FormatBool(req.GetOptBool()))
					queries.Add("wrap_bool", strconv.FormatBool(req.GetWrapBool().GetValue()))
					queries.Add("int32", strconv.FormatInt(int64(req.GetInt32()), 10))
					queries.Add("sint32", strconv.FormatInt(int64(req.GetSint32()), 10))
					queries.Add("sfixed32", strconv.FormatInt(int64(req.GetSfixed32()), 10))
					queries.Add("opt_int32", strconv.FormatInt(int64(req.GetOptInt32()), 10))
					queries.Add("opt_sint32", strconv.FormatInt(int64(req.GetOptSint32()), 10))
					queries.Add("opt_sfixed32", strconv.FormatInt(int64(req.GetOptSfixed32()), 10))
					queries.Add("wrap_int32", strconv.FormatInt(int64(req.GetWrapInt32().GetValue()), 10))
					queries.Add("int64", strconv.FormatInt(req.GetInt64(), 10))
					queries.Add("sint64", strconv.FormatInt(req.GetSint64(), 10))
					queries.Add("sfixed64", strconv.FormatInt(req.GetSfixed64(), 10))
					queries.Add("opt_int64", strconv.FormatInt(req.GetOptInt64(), 10))
					queries.Add("opt_sint64", strconv.FormatInt(req.GetOptSint64(), 10))
					queries.Add("opt_sfixed64", strconv.FormatInt(req.GetOptSfixed64(), 10))
					queries.Add("wrap_int64", strconv.FormatInt(req.GetWrapInt64().GetValue(), 10))
					queries.Add("uint32", strconv.FormatUint(uint64(req.GetUint32()), 10))
					queries.Add("fixed32", strconv.FormatUint(uint64(req.GetFixed32()), 10))
					queries.Add("opt_uint32", strconv.FormatUint(uint64(req.GetOptUint32()), 10))
					queries.Add("opt_fixed32", strconv.FormatUint(uint64(req.GetOptFixed32()), 10))
					queries.Add("wrap_uint32", strconv.FormatUint(uint64(req.GetWrapUint32().GetValue()), 10))
					queries.Add("uint64", strconv.FormatUint(req.GetUint64(), 10))
					queries.Add("fixed64", strconv.FormatUint(req.GetFixed64(), 10))
					queries.Add("opt_uint64", strconv.FormatUint(req.GetOptUint64(), 10))
					queries.Add("opt_fixed64", strconv.FormatUint(req.GetOptFixed64(), 10))
					queries.Add("wrap_uint64", strconv.FormatUint(req.GetWrapUint64().GetValue(), 10))
					queries.Add("float", strconv.FormatFloat(float64(req.GetFloat()), 'f', -1, 32))
					queries.Add("opt_float", strconv.FormatFloat(float64(req.GetOptFloat()), 'f', -1, 32))
					queries.Add("wrap_float", strconv.FormatFloat(float64(req.GetWrapFloat().GetValue()), 'f', -1, 32))
					queries.Add("double", strconv.FormatFloat(req.GetDouble(), 'f', -1, 64))
					queries.Add("opt_double", strconv.FormatFloat(req.GetOptDouble(), 'f', -1, 64))
					queries.Add("wrap_double", strconv.FormatFloat(req.GetWrapDouble().GetValue(), 'f', -1, 64))
					queries.Add("string", req.GetString_())
					queries.Add("opt_string", req.GetOptString())
					queries.Add("wrap_string", req.GetWrapString().GetValue())
					target := &url.URL{
						Scheme:   scheme,
						Host:     instance,
						Path:     path.Path,
						RawQuery: queries.Encode(),
					}
					r, err := http1.NewRequestWithContext(ctx, "GET", target.String(), body)
					if err != nil {
						return nil, err
					}
					return r, nil
				},
				func(ctx context.Context, r *http1.Response) (interface{}, error) {
					return nil, nil
				},
				opts...,
			).Endpoint(),
			mdw...),
	}
}
