#!/bin/sh

cd ./log/slog
go get -u codeup.aliyun.com/qimao/leo/leo
go mod tidy
cd ../../

cd ./log/zaplog
go get -u codeup.aliyun.com/qimao/leo/leo
go mod tidy
cd ../../

cd ./schedule/cron
go get -u codeup.aliyun.com/qimao/leo/leo
go mod tidy
cd ../../


cd ./transport/ginhttp
go get -u codeup.aliyun.com/qimao/leo/leo
go mod tidy
cd ../../
