// Code generated by protoc-gen-go-leo. DO NOT EDIT.

package route

import (
	context "context"
	cqrs "github.com/go-leo/leo/v3/cqrs"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

func NewBoolQueryCqrsService[
	BoolQueryCommandType BoolQueryCommand,
](
	boolQueryHandler cqrs.CommandHandler[BoolQueryCommandType],
) (BoolQueryService, error) {
	var bus cqrs.SampleBus
	if err := bus.RegisterCommand(boolQueryHandler); err != nil {
		return nil, err
	}
	return &boolQueryCqrsService{bus: &bus}, nil
}

func NewInt32QueryCqrsService[
	Int32QueryCommandType Int32QueryCommand,
](
	int32QueryHandler cqrs.CommandHandler[Int32QueryCommandType],
) (Int32QueryService, error) {
	var bus cqrs.SampleBus
	if err := bus.RegisterCommand(int32QueryHandler); err != nil {
		return nil, err
	}
	return &int32QueryCqrsService{bus: &bus}, nil
}

func NewInt64QueryCqrsService[
	Int64QueryCommandType Int64QueryCommand,
](
	int64QueryHandler cqrs.CommandHandler[Int64QueryCommandType],
) (Int64QueryService, error) {
	var bus cqrs.SampleBus
	if err := bus.RegisterCommand(int64QueryHandler); err != nil {
		return nil, err
	}
	return &int64QueryCqrsService{bus: &bus}, nil
}

func NewUint32QueryCqrsService[
	Uint32QueryCommandType Uint32QueryCommand,
](
	uint32QueryHandler cqrs.CommandHandler[Uint32QueryCommandType],
) (Uint32QueryService, error) {
	var bus cqrs.SampleBus
	if err := bus.RegisterCommand(uint32QueryHandler); err != nil {
		return nil, err
	}
	return &uint32QueryCqrsService{bus: &bus}, nil
}

func NewUint64QueryCqrsService[
	Uint64QueryCommandType Uint64QueryCommand,
](
	uint64QueryHandler cqrs.CommandHandler[Uint64QueryCommandType],
) (Uint64QueryService, error) {
	var bus cqrs.SampleBus
	if err := bus.RegisterCommand(uint64QueryHandler); err != nil {
		return nil, err
	}
	return &uint64QueryCqrsService{bus: &bus}, nil
}

func NewFloatQueryCqrsService[
	FloatQueryCommandType FloatQueryCommand,
](
	floatQueryHandler cqrs.CommandHandler[FloatQueryCommandType],
) (FloatQueryService, error) {
	var bus cqrs.SampleBus
	if err := bus.RegisterCommand(floatQueryHandler); err != nil {
		return nil, err
	}
	return &floatQueryCqrsService{bus: &bus}, nil
}

func NewDoubleQueryCqrsService[
	DoubleQueryCommandType DoubleQueryCommand,
](
	doubleQueryHandler cqrs.CommandHandler[DoubleQueryCommandType],
) (DoubleQueryService, error) {
	var bus cqrs.SampleBus
	if err := bus.RegisterCommand(doubleQueryHandler); err != nil {
		return nil, err
	}
	return &doubleQueryCqrsService{bus: &bus}, nil
}

func NewStringQueryCqrsService[
	StringQueryCommandType StringQueryCommand,
](
	stringQueryHandler cqrs.CommandHandler[StringQueryCommandType],
) (StringQueryService, error) {
	var bus cqrs.SampleBus
	if err := bus.RegisterCommand(stringQueryHandler); err != nil {
		return nil, err
	}
	return &stringQueryCqrsService{bus: &bus}, nil
}

func NewEnumQueryCqrsService[
	EnumQueryCommandType EnumQueryCommand,
](
	enumQueryHandler cqrs.CommandHandler[EnumQueryCommandType],
) (EnumQueryService, error) {
	var bus cqrs.SampleBus
	if err := bus.RegisterCommand(enumQueryHandler); err != nil {
		return nil, err
	}
	return &enumQueryCqrsService{bus: &bus}, nil
}

type boolQueryCqrsService struct {
	bus cqrs.Bus
}

func (svc *boolQueryCqrsService) BoolQuery(ctx context.Context, request *BoolQueryRequest) (*emptypb.Empty, error) {
	var command BoolQueryCommand
	command, ctx, err := command.From(ctx, request)
	if err != nil {
		return nil, err
	}

	if err := svc.bus.Exec(ctx, command); err != nil {
		return nil, err
	}
	return new(emptypb.Empty), nil
}

type (
	BoolQueryCommand interface {
		isBoolQueryCommand_Kind()
		From(context.Context, *BoolQueryRequest) (BoolQueryCommand, context.Context, error)
	}
	UnimplementedBoolQueryCommand struct{}
)

func (UnimplementedBoolQueryCommand) isBoolQueryCommand_Kind() {}
func (UnimplementedBoolQueryCommand) From(context.Context, *BoolQueryRequest) (BoolQueryCommand, context.Context, error) {
	panic("implement me")
	return nil, nil, nil
}

type int32QueryCqrsService struct {
	bus cqrs.Bus
}

func (svc *int32QueryCqrsService) Int32Query(ctx context.Context, request *Int32QueryRequest) (*emptypb.Empty, error) {
	var command Int32QueryCommand
	command, ctx, err := command.From(ctx, request)
	if err != nil {
		return nil, err
	}

	if err := svc.bus.Exec(ctx, command); err != nil {
		return nil, err
	}
	return new(emptypb.Empty), nil
}

type (
	Int32QueryCommand interface {
		isInt32QueryCommand_Kind()
		From(context.Context, *Int32QueryRequest) (Int32QueryCommand, context.Context, error)
	}
	UnimplementedInt32QueryCommand struct{}
)

func (UnimplementedInt32QueryCommand) isInt32QueryCommand_Kind() {}
func (UnimplementedInt32QueryCommand) From(context.Context, *Int32QueryRequest) (Int32QueryCommand, context.Context, error) {
	panic("implement me")
	return nil, nil, nil
}

type int64QueryCqrsService struct {
	bus cqrs.Bus
}

func (svc *int64QueryCqrsService) Int64Query(ctx context.Context, request *Int64QueryRequest) (*emptypb.Empty, error) {
	var command Int64QueryCommand
	command, ctx, err := command.From(ctx, request)
	if err != nil {
		return nil, err
	}

	if err := svc.bus.Exec(ctx, command); err != nil {
		return nil, err
	}
	return new(emptypb.Empty), nil
}

type (
	Int64QueryCommand interface {
		isInt64QueryCommand_Kind()
		From(context.Context, *Int64QueryRequest) (Int64QueryCommand, context.Context, error)
	}
	UnimplementedInt64QueryCommand struct{}
)

func (UnimplementedInt64QueryCommand) isInt64QueryCommand_Kind() {}
func (UnimplementedInt64QueryCommand) From(context.Context, *Int64QueryRequest) (Int64QueryCommand, context.Context, error) {
	panic("implement me")
	return nil, nil, nil
}

type uint32QueryCqrsService struct {
	bus cqrs.Bus
}

func (svc *uint32QueryCqrsService) Uint32Query(ctx context.Context, request *Uint32QueryRequest) (*emptypb.Empty, error) {
	var command Uint32QueryCommand
	command, ctx, err := command.From(ctx, request)
	if err != nil {
		return nil, err
	}

	if err := svc.bus.Exec(ctx, command); err != nil {
		return nil, err
	}
	return new(emptypb.Empty), nil
}

type (
	Uint32QueryCommand interface {
		isUint32QueryCommand_Kind()
		From(context.Context, *Uint32QueryRequest) (Uint32QueryCommand, context.Context, error)
	}
	UnimplementedUint32QueryCommand struct{}
)

func (UnimplementedUint32QueryCommand) isUint32QueryCommand_Kind() {}
func (UnimplementedUint32QueryCommand) From(context.Context, *Uint32QueryRequest) (Uint32QueryCommand, context.Context, error) {
	panic("implement me")
	return nil, nil, nil
}

type uint64QueryCqrsService struct {
	bus cqrs.Bus
}

func (svc *uint64QueryCqrsService) Uint64Query(ctx context.Context, request *Uint64QueryRequest) (*emptypb.Empty, error) {
	var command Uint64QueryCommand
	command, ctx, err := command.From(ctx, request)
	if err != nil {
		return nil, err
	}

	if err := svc.bus.Exec(ctx, command); err != nil {
		return nil, err
	}
	return new(emptypb.Empty), nil
}

type (
	Uint64QueryCommand interface {
		isUint64QueryCommand_Kind()
		From(context.Context, *Uint64QueryRequest) (Uint64QueryCommand, context.Context, error)
	}
	UnimplementedUint64QueryCommand struct{}
)

func (UnimplementedUint64QueryCommand) isUint64QueryCommand_Kind() {}
func (UnimplementedUint64QueryCommand) From(context.Context, *Uint64QueryRequest) (Uint64QueryCommand, context.Context, error) {
	panic("implement me")
	return nil, nil, nil
}

type floatQueryCqrsService struct {
	bus cqrs.Bus
}

func (svc *floatQueryCqrsService) FloatQuery(ctx context.Context, request *FloatQueryRequest) (*emptypb.Empty, error) {
	var command FloatQueryCommand
	command, ctx, err := command.From(ctx, request)
	if err != nil {
		return nil, err
	}

	if err := svc.bus.Exec(ctx, command); err != nil {
		return nil, err
	}
	return new(emptypb.Empty), nil
}

type (
	FloatQueryCommand interface {
		isFloatQueryCommand_Kind()
		From(context.Context, *FloatQueryRequest) (FloatQueryCommand, context.Context, error)
	}
	UnimplementedFloatQueryCommand struct{}
)

func (UnimplementedFloatQueryCommand) isFloatQueryCommand_Kind() {}
func (UnimplementedFloatQueryCommand) From(context.Context, *FloatQueryRequest) (FloatQueryCommand, context.Context, error) {
	panic("implement me")
	return nil, nil, nil
}

type doubleQueryCqrsService struct {
	bus cqrs.Bus
}

func (svc *doubleQueryCqrsService) DoubleQuery(ctx context.Context, request *DoubleQueryRequest) (*emptypb.Empty, error) {
	var command DoubleQueryCommand
	command, ctx, err := command.From(ctx, request)
	if err != nil {
		return nil, err
	}

	if err := svc.bus.Exec(ctx, command); err != nil {
		return nil, err
	}
	return new(emptypb.Empty), nil
}

type (
	DoubleQueryCommand interface {
		isDoubleQueryCommand_Kind()
		From(context.Context, *DoubleQueryRequest) (DoubleQueryCommand, context.Context, error)
	}
	UnimplementedDoubleQueryCommand struct{}
)

func (UnimplementedDoubleQueryCommand) isDoubleQueryCommand_Kind() {}
func (UnimplementedDoubleQueryCommand) From(context.Context, *DoubleQueryRequest) (DoubleQueryCommand, context.Context, error) {
	panic("implement me")
	return nil, nil, nil
}

type stringQueryCqrsService struct {
	bus cqrs.Bus
}

func (svc *stringQueryCqrsService) StringQuery(ctx context.Context, request *StringQueryRequest) (*emptypb.Empty, error) {
	var command StringQueryCommand
	command, ctx, err := command.From(ctx, request)
	if err != nil {
		return nil, err
	}

	if err := svc.bus.Exec(ctx, command); err != nil {
		return nil, err
	}
	return new(emptypb.Empty), nil
}

type (
	StringQueryCommand interface {
		isStringQueryCommand_Kind()
		From(context.Context, *StringQueryRequest) (StringQueryCommand, context.Context, error)
	}
	UnimplementedStringQueryCommand struct{}
)

func (UnimplementedStringQueryCommand) isStringQueryCommand_Kind() {}
func (UnimplementedStringQueryCommand) From(context.Context, *StringQueryRequest) (StringQueryCommand, context.Context, error) {
	panic("implement me")
	return nil, nil, nil
}

type enumQueryCqrsService struct {
	bus cqrs.Bus
}

func (svc *enumQueryCqrsService) EnumQuery(ctx context.Context, request *EnumQueryRequest) (*emptypb.Empty, error) {
	var command EnumQueryCommand
	command, ctx, err := command.From(ctx, request)
	if err != nil {
		return nil, err
	}

	if err := svc.bus.Exec(ctx, command); err != nil {
		return nil, err
	}
	return new(emptypb.Empty), nil
}

type (
	EnumQueryCommand interface {
		isEnumQueryCommand_Kind()
		From(context.Context, *EnumQueryRequest) (EnumQueryCommand, context.Context, error)
	}
	UnimplementedEnumQueryCommand struct{}
)

func (UnimplementedEnumQueryCommand) isEnumQueryCommand_Kind() {}
func (UnimplementedEnumQueryCommand) From(context.Context, *EnumQueryRequest) (EnumQueryCommand, context.Context, error) {
	panic("implement me")
	return nil, nil, nil
}

// route/v1/cq/bool_query_leo.query.pb.go
// route/v1/cq/int32_query_leo.query.pb.go
// route/v1/cq/int64_query_leo.query.pb.go
// route/v1/cq/uint32_query_leo.query.pb.go
// route/v1/cq/uint64_query_leo.query.pb.go
// route/v1/cq/float_query_leo.query.pb.go
// route/v1/cq/double_query_leo.query.pb.go
// route/v1/cq/string_query_leo.query.pb.go
// route/v1/cq/enum_query_leo.query.pb.go
