// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package body

import (
	cqrs "github.com/go-leo/leo/v3/cqrs"
)

// BodyAssembler responsible for completing the transformation between domain model objects and DTOs
type BodyAssembler interface {
}

// BodyCQRSService implement the Body service with CQRS pattern
type BodyCQRSService struct {
	bus       cqrs.Bus
	assembler BodyAssembler
}

func NewBodyCQRSService(bus cqrs.Bus, assembler BodyAssembler) *BodyCQRSService {
	return &BodyCQRSService{bus: bus, assembler: assembler}
}

func NewBodyBus() (cqrs.Bus, error) {
	bus := cqrs.NewBus()
	return bus, nil
}
