// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package cqrs

import (
	context "context"
	endpoint "github.com/go-kit/kit/endpoint"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

type cQRSEndpoints struct {
	svc interface {
		CreateUser(ctx context.Context, request *CreateUserRequest) (*emptypb.Empty, error)
		FindUser(ctx context.Context, request *FindUserRequest) (*GetUserResponse, error)
	}
}

func (e *cQRSEndpoints) CreateUser() endpoint.Endpoint {
	return func(ctx context.Context, request any) (any, error) {
		return e.svc.CreateUser(ctx, request.(*CreateUserRequest))
	}
}

func (e *cQRSEndpoints) FindUser() endpoint.Endpoint {
	return func(ctx context.Context, request any) (any, error) {
		return e.svc.FindUser(ctx, request.(*FindUserRequest))
	}
}

func NewCQRSEndpoints(
	svc interface {
		CreateUser(ctx context.Context, request *CreateUserRequest) (*emptypb.Empty, error)
		FindUser(ctx context.Context, request *FindUserRequest) (*GetUserResponse, error)
	},
) interface {
	CreateUser() endpoint.Endpoint
	FindUser() endpoint.Endpoint
} {
	return &cQRSEndpoints{svc: svc}
}
