// Code generated by protoc-gen-go-leo. DO NOT EDIT.
// If you want edit it, can move this file to another directory.

package cq

import (
	context "context"
	cqrs "github.com/go-leo/leo/v3/cqrs"
	v1 "github.com/go-leo/leo/v3/example/api/route/v1"
)

var _ EnumPathHandler = (*enumPathHandler)(nil)

type EnumPathHandler cqrs.CommandHandler[EnumPathCommand]

type EnumPathCommand struct {
	v1.UnimplementedEnumPathCommand
}

func (EnumPathCommand) From(ctx context.Context, req *v1.EnumPathRequest) (v1.EnumPathCommand, context.Context, error) {
	panic("implement me")
	return EnumPathCommand{}, ctx, nil
}

func NewEnumPathHandler() EnumPathHandler {
	return &enumPathHandler{}
}

type enumPathHandler struct {
}

func (h *enumPathHandler) Handle(ctx context.Context, cmd EnumPathCommand) error {
	// TODO implement me
	panic("implement me")
}
