// Code generated by protoc-gen-go-leo. DO NOT EDIT.
// If you want edit it, can move this file to another directory.

package cq

import (
	context "context"
	cqrs "github.com/go-leo/leo/v3/cqrs"
	v1 "github.com/go-leo/leo/v3/example/api/route/v1"
)

var _ FloatPathHandler = (*floatPathHandler)(nil)

type FloatPathHandler cqrs.CommandHandler[FloatPathCommand]

type FloatPathCommand struct {
	v1.UnimplementedFloatPathCommand
}

func NewFloatPathHandler() FloatPathHandler {
	return &floatPathHandler{}
}

type floatPathHandler struct {
}

func (h *floatPathHandler) Handle(ctx context.Context, cmd FloatPathCommand) error {
	// TODO implement me
	panic("implement me")
}
