// Code generated by protoc-gen-go-leo. DO NOT EDIT.
// If you want edit it, can move this file to another directory.

package cq

import (
	context "context"
	cqrs "github.com/go-leo/leo/v3/cqrs"
	v1 "github.com/go-leo/leo/v3/example/api/route/v1"
)

var _ HttpBodyNamedResponseHandler = (*httpBodyNamedResponseHandler)(nil)

type HttpBodyNamedResponseHandler cqrs.QueryHandler[HttpBodyNamedResponseQuery, HttpBodyNamedResponseResult]

type HttpBodyNamedResponseQuery struct {
	v1.UnimplementedHttpBodyNamedResponseQuery
}

type HttpBodyNamedResponseResult struct {
	v1.UnimplementedHttpBodyNamedResponseResult
}

func NewHttpBodyNamedResponseHandler() HttpBodyNamedResponseHandler {
	return &httpBodyNamedResponseHandler{}
}

type httpBodyNamedResponseHandler struct {
}

func (h *httpBodyNamedResponseHandler) Handle(ctx context.Context, q HttpBodyNamedResponseQuery) (HttpBodyNamedResponseResult, error) {
	// TODO implement me
	panic("implement me")
}
