// Code generated by protoc-gen-go-leo. DO NOT EDIT.
// If you want edit it, can move this file to another directory.

package cq

import (
	context "context"
	cqrs "github.com/go-leo/leo/v3/cqrs"
	v1 "github.com/go-leo/leo/v3/example/api/route/v1"
)

var _ NamedPathStringHandler = (*namedPathStringHandler)(nil)

type NamedPathStringHandler cqrs.CommandHandler[NamedPathStringCommand]

type NamedPathStringCommand struct {
	v1.UnimplementedNamedPathStringCommand
}

func (NamedPathStringCommand) From(ctx context.Context, req *v1.NamedPathRequest) (v1.NamedPathStringCommand, context.Context, error) {
	panic("implement me")
	return NamedPathStringCommand{}, ctx, nil
}

func NewNamedPathStringHandler() NamedPathStringHandler {
	return &namedPathStringHandler{}
}

type namedPathStringHandler struct {
}

func (h *namedPathStringHandler) Handle(ctx context.Context, cmd NamedPathStringCommand) error {
	// TODO implement me
	panic("implement me")
}
