// Code generated by protoc-gen-go-leo. DO NOT EDIT.
// If you want edit it, can move this file to another directory.

package cq

import (
	context "context"
	cqrs "github.com/go-leo/leo/v3/cqrs"
	v1 "github.com/go-leo/leo/v3/example/api/route/v1"
)

var _ StarResponseHandler = (*starResponseHandler)(nil)

type StarResponseHandler cqrs.QueryHandler[StarResponseQuery, StarResponseResult]

type StarResponseQuery struct {
	v1.UnimplementedStarResponseQuery
}

type StarResponseResult struct {
	v1.UnimplementedStarResponseResult
}

func NewStarResponseHandler() StarResponseHandler {
	return &starResponseHandler{}
}

type starResponseHandler struct {
}

func (h *starResponseHandler) Handle(ctx context.Context, q StarResponseQuery) (StarResponseResult, error) {
	// TODO implement me
	panic("implement me")
}
